--- BLOCK #0 1-14, warpins: 1 ---
slot0 = require
slot2 = "Core.Framework.Class"
slot0 = slot0(slot2)
slot1 = require
slot3 = "Guis.UIView"
slot1 = slot1(slot3)
slot2 = slot0.LightClass
slot4 = "InfoPlayerCardView"
slot5 = slot1
slot2 = slot2(slot4, slot5)

slot3 = function(slot0)
	--- BLOCK #0 1-205, warpins: 1 ---
	slot1 = slot0.transform
	slot3 = slot1
	slot1 = slot1.GetComponent
	slot4 = "ObjectReference"
	slot1 = slot1(slot3, slot4)
	slot0.objectReference = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "btnCloseFullScreenButton"
	slot1 = slot1(slot3, slot4)
	slot0.btnCloseFullScreenButton = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "popupUPopupForm"
	slot1 = slot1(slot3, slot4)
	slot0.popupUPopupForm = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "infoPlayerCardWidget"
	slot1 = slot1(slot3, slot4)
	slot0.infoPlayerCardWidget = slot1
	slot1 = slot0.infoPlayerCardWidget
	slot1 = slot1.transform
	slot3 = slot1
	slot1 = slot1.GetComponent
	slot4 = "ObjectReference"
	slot1 = slot1(slot3, slot4)
	slot0.infoPlayerPanelObjectReference = slot1
	slot1 = slot0.infoPlayerCardWidget
	slot1 = slot1.transform
	slot3 = slot1
	slot1 = slot1.GetComponent
	slot4 = "UComponent"
	slot1 = slot1(slot3, slot4)
	slot0.rootUComponent = slot1
	slot1 = slot0.infoPlayerPanelObjectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "playerNameText"
	slot1 = slot1(slot3, slot4)
	slot0.playerNameText = slot1
	slot1 = slot0.infoPlayerPanelObjectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "playerSignText"
	slot1 = slot1(slot3, slot4)
	slot0.playerSignText = slot1
	slot1 = slot0.infoPlayerPanelObjectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "uidText"
	slot1 = slot1(slot3, slot4)
	slot0.uidText = slot1
	slot1 = slot0.infoPlayerPanelObjectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "closeBtn"
	slot1 = slot1(slot3, slot4)
	slot0.closeBtn = slot1
	slot1 = slot0.infoPlayerPanelObjectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "headBtn"
	slot1 = slot1(slot3, slot4)
	slot0.headBtn = slot1
	slot1 = slot0.infoPlayerPanelObjectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "emblemImage"
	slot1 = slot1(slot3, slot4)
	slot0.emblemImage = slot1
	slot1 = slot0.infoPlayerPanelObjectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "playerNameChangeText"
	slot1 = slot1(slot3, slot4)
	slot0.playerNameChangeText = slot1
	slot1 = slot0.infoPlayerPanelObjectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "nameCoverText"
	slot1 = slot1(slot3, slot4)
	slot0.nameCoverText = slot1
	slot1 = slot0.infoPlayerPanelObjectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "btnFollow"
	slot1 = slot1(slot3, slot4)
	slot0.btnFollow = slot1
	slot1 = slot0.infoPlayerPanelObjectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "followNameText"
	slot1 = slot1(slot3, slot4)
	slot0.followNameText = slot1
	slot1 = slot0.infoPlayerPanelObjectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "classNumText"
	slot1 = slot1(slot3, slot4)
	slot0.classNumText = slot1
	slot1 = slot0.infoPlayerPanelObjectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "classInfoText"
	slot1 = slot1(slot3, slot4)
	slot0.classInfoText = slot1
	slot1 = slot0.infoPlayerPanelObjectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "copyBtn"
	slot1 = slot1(slot3, slot4)
	slot0.copyBtn = slot1
	slot1 = slot0.infoPlayerPanelObjectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "levelText"
	slot1 = slot1(slot3, slot4)
	slot0.levelText = slot1
	slot1 = slot0.infoPlayerPanelObjectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "interactBtnList"
	slot1 = slot1(slot3, slot4)
	slot0.interactBtnList = slot1
	slot1 = slot0.infoPlayerPanelObjectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "teamBtn"
	slot1 = slot1(slot3, slot4)
	slot0.teamBtn = slot1
	slot1 = slot0.infoPlayerPanelObjectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "teamNumText"
	slot1 = slot1(slot3, slot4)
	slot0.teamNumText = slot1
	slot1 = slot0.infoPlayerPanelObjectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "teamNameText"
	slot1 = slot1(slot3, slot4)
	slot0.teamNameText = slot1
	slot1 = slot0.infoPlayerPanelObjectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "playerBgImage"
	slot1 = slot1(slot3, slot4)
	slot0.playerBgImage = slot1
	slot1 = slot0.infoPlayerPanelObjectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "btnGatherUButton"
	slot1 = slot1(slot3, slot4)
	slot0.btnGatherUButton = slot1
	slot1 = slot0.infoPlayerPanelObjectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "collectNumUSDFText"
	slot1 = slot1(slot3, slot4)
	slot0.collectNumUSDFText = slot1
	slot1 = slot0.infoPlayerPanelObjectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "btnVoiceUButton"
	slot1 = slot1(slot3, slot4)
	slot0.btnVoiceUButton = slot1
	slot1 = slot0.infoPlayerPanelObjectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "listTogetherUList"
	slot1 = slot1(slot3, slot4)
	slot0.listTogetherUList = slot1
	slot1 = slot0.infoPlayerPanelObjectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "togetherUWidget"
	slot1 = slot1(slot3, slot4)
	slot0.togetherUWidget = slot1
	slot1 = slot0.infoPlayerPanelObjectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "hongGatherUButton"
	slot1 = slot1(slot3, slot4)
	slot0.hongGatherUButton = slot1
	slot1 = slot0.hongGatherUButton
	slot3 = slot1
	slot1 = slot1.GetComponent
	slot4 = "ObjectReference"
	slot1 = slot1(slot3, slot4)
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "txtNameUSDFText"
	slot2 = slot2(slot4, slot5)
	slot0.hongGatherTxtNameUSDFText = slot2
	slot2 = slot0.infoPlayerPanelObjectReference
	slot4 = slot2
	slot2 = slot2.GetRefValue
	slot5 = "listBadgeUList"
	slot2 = slot2(slot4, slot5)
	slot0.listBadgeUList = slot2

	return
	--- END OF BLOCK #0 ---



end

slot2.findObjects = slot3

return slot2
--- END OF BLOCK #0 ---



