--- BLOCK #0 1-24, warpins: 1 ---
slot0 = require
slot2 = "Core.Log.LoggerManager"
slot0 = slot0(slot2)
slot0 = slot0.getLogger
slot2 = "GrabEggsModeView"
slot0 = slot0(slot2)
slot1 = require
slot3 = "Core.Framework.Class"
slot1 = slot1(slot3)
slot2 = require
slot4 = "Guis.UIView"
slot2 = slot2(slot4)
slot3 = slot1.LightClass
slot5 = "GrabEggsModeView"
slot6 = slot2
slot3 = slot3(slot5, slot6)

slot4 = function(slot0)
	--- BLOCK #0 1-344, warpins: 1 ---
	slot1 = slot0.transform
	slot3 = slot1
	slot1 = slot1.GetComponent
	slot4 = "ObjectReference"
	slot1 = slot1(slot3, slot4)
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "bg"
	slot2 = slot2(slot4, slot5)
	slot0.bg = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "oldBg"
	slot2 = slot2(slot4, slot5)
	slot0.oldBg = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "peopleImg"
	slot2 = slot2(slot4, slot5)
	slot0.peopleImg = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "oldPeopleImg"
	slot2 = slot2(slot4, slot5)
	slot0.oldPeopleImg = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "btnBackUButton"
	slot2 = slot2(slot4, slot5)
	slot0.btnBackUButton = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "btnConfirmUButton"
	slot2 = slot2(slot4, slot5)
	slot0.btnConfirmUButton = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "dungeonNameUText"
	slot2 = slot2(slot4, slot5)
	slot0.dungeonNameUText = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "dungeonScrollRect"
	slot2 = slot2(slot4, slot5)
	slot0.dungeonScrollRect = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "dangerousTip"
	slot2 = slot2(slot4, slot5)
	slot0.dangerousTip = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "gradTxt"
	slot2 = slot2(slot4, slot5)
	slot0.gradTxt = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "rewardUList"
	slot2 = slot2(slot4, slot5)
	slot0.rewardUList = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "peopleNumUBaseText"
	slot2 = slot2(slot4, slot5)
	slot0.peopleNumUBaseText = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "rewardUWidget"
	slot2 = slot2(slot4, slot5)
	slot0.rewardUWidget = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "rewardList"
	slot2 = slot2(slot4, slot5)
	slot0.rewardList = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "backTitle"
	slot2 = slot2(slot4, slot5)
	slot0.backTitle = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "selectorUSelector"
	slot2 = slot2(slot4, slot5)
	slot0.selectorUSelector = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "btnGoToUButton"
	slot2 = slot2(slot4, slot5)
	slot0.btnGoToUButton = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "waitUWidget"
	slot2 = slot2(slot4, slot5)
	slot0.waitUWidget = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "textWarningTip"
	slot2 = slot2(slot4, slot5)
	slot0.textWarningTip = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "btnTeam1UButton"
	slot2 = slot2(slot4, slot5)
	slot0.btnTeam1UButton = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "btnTeam2UButton"
	slot2 = slot2(slot4, slot5)
	slot0.btnTeam2UButton = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "btnTeam3UButton"
	slot2 = slot2(slot4, slot5)
	slot0.btnTeam3UButton = slot2
	slot2 = slot0.btnTeam1UButton
	slot2 = slot2.transform
	slot4 = slot2
	slot2 = slot2.GetComponent
	slot5 = "ObjectReference"
	slot2 = slot2(slot4, slot5)
	slot5 = slot2
	slot3 = slot2.GetRefValue
	slot6 = "chaosName"
	slot3 = slot3(slot5, slot6)
	slot0.chaosName = slot3
	slot5 = slot2
	slot3 = slot2.GetRefValue
	slot6 = "chaosName2"
	slot3 = slot3(slot5, slot6)
	slot0.chaosName2 = slot3
	slot5 = slot1
	slot3 = slot1.GetRefValue
	slot6 = "textTeamNum"
	slot3 = slot3(slot5, slot6)
	slot0.textTeamNum = slot3
	slot5 = slot1
	slot3 = slot1.GetRefValue
	slot6 = "currencyItem"
	slot3 = slot3(slot5, slot6)
	slot0.currencyItem = slot3
	slot5 = slot1
	slot3 = slot1.GetRefValue
	slot6 = "textTimeLimit"
	slot3 = slot3(slot5, slot6)
	slot0.textTimeLimit = slot3
	slot5 = slot1
	slot3 = slot1.GetRefValue
	slot6 = "textLvLimit"
	slot3 = slot3(slot5, slot6)
	slot0.textLvLimit = slot3
	slot5 = slot1
	slot3 = slot1.GetRefValue
	slot6 = "textPetLvLimit"
	slot3 = slot3(slot5, slot6)
	slot0.textPetLvLimit = slot3
	slot5 = slot1
	slot3 = slot1.GetRefValue
	slot6 = "textWarningTip"
	slot3 = slot3(slot5, slot6)
	slot0.textWarningTip = slot3
	slot5 = slot1
	slot3 = slot1.GetRefValue
	slot6 = "btnStoreUButton"
	slot3 = slot3(slot5, slot6)
	slot0.btnStoreUButton = slot3
	slot5 = slot1
	slot3 = slot1.GetRefValue
	slot6 = "btnEquipUButton"
	slot3 = slot3(slot5, slot6)
	slot0.btnEquipUButton = slot3
	slot5 = slot1
	slot3 = slot1.GetRefValue
	slot6 = "btnTalentUButton"
	slot3 = slot3(slot5, slot6)
	slot0.btnTalentUButton = slot3
	slot5 = slot1
	slot3 = slot1.GetRefValue
	slot6 = "textTimeTips"
	slot3 = slot3(slot5, slot6)
	slot0.textTimeTips = slot3
	slot5 = slot1
	slot3 = slot1.GetRefValue
	slot6 = "txtNameUSDFText"
	slot3 = slot3(slot5, slot6)
	slot0.txtNameUSDFText = slot3
	slot5 = slot1
	slot3 = slot1.GetRefValue
	slot6 = "keyR3HotKeyContent"
	slot3 = slot3(slot5, slot6)
	slot0.keyR3HotKeyContent = slot3
	slot5 = slot1
	slot3 = slot1.GetRefValue
	slot6 = "consoleBar"
	slot3 = slot3(slot5, slot6)
	slot0.consoleBar = slot3
	slot5 = slot1
	slot3 = slot1.GetRefValue
	slot6 = "skillList"
	slot3 = slot3(slot5, slot6)
	slot0.skillList = slot3
	slot5 = slot1
	slot3 = slot1.GetRefValue
	slot6 = "seasonInfoUContainer"
	slot3 = slot3(slot5, slot6)
	slot0.seasonInfoUContainer = slot3
	slot5 = slot1
	slot3 = slot1.GetRefValue
	slot6 = "protectUSDFText"
	slot3 = slot3(slot5, slot6)
	slot0.protectUSDFText = slot3
	slot5 = slot1
	slot3 = slot1.GetRefValue
	slot6 = "btnInfoUButton"
	slot3 = slot3(slot5, slot6)
	slot0.btnInfoUButton = slot3
	slot5 = slot1
	slot3 = slot1.GetRefValue
	slot6 = "iconUp3USDFText"
	slot3 = slot3(slot5, slot6)
	slot0.iconUp3USDFText = slot3
	slot5 = slot1
	slot3 = slot1.GetRefValue
	slot6 = "iconUp3UButton"
	slot3 = slot3(slot5, slot6)
	slot0.iconUp3UButton = slot3
	slot5 = slot1
	slot3 = slot1.GetRefValue
	slot6 = "upTipUContainer"
	slot3 = slot3(slot5, slot6)
	slot0.upTipUContainer = slot3
	slot5 = slot1
	slot3 = slot1.GetRefValue
	slot6 = "dropHintUContainer"
	slot3 = slot3(slot5, slot6)
	slot0.dropHintUContainer = slot3
	slot5 = slot1
	slot3 = slot1.GetRefValue
	slot6 = "posterUContainer"
	slot3 = slot3(slot5, slot6)
	slot0.propagandaPoster = slot3
	slot3 = slot0.propagandaPoster
	slot5 = slot3
	slot3 = slot3.SetActive
	slot6 = false

	slot3(slot5, slot6)

	slot3 = slot0.transform
	slot5 = slot3
	slot3 = slot3.GetComponent
	slot6 = "UComponent"
	slot3 = slot3(slot5, slot6)
	slot0.rootUWidget = slot3
	slot5 = slot1
	slot3 = slot1.GetRefValue
	slot6 = "txtLimitNameUSDFText"
	slot3 = slot3(slot5, slot6)
	slot0.txtLimitNameUSDFText = slot3
	slot5 = slot1
	slot3 = slot1.GetRefValue
	slot6 = "btnForgingUButton"
	slot3 = slot3(slot5, slot6)
	slot0.btnForgingUButton = slot3
	slot5 = slot1
	slot3 = slot1.GetRefValue
	slot6 = "btnCollectionUButton"
	slot3 = slot3(slot5, slot6)
	slot0.btnCollectionUButton = slot3
	slot3 = slot0.btnTalentUButton
	slot3 = slot3.transform
	slot5 = slot3
	slot3 = slot3.GetComponent
	slot6 = "ObjectReference"
	slot3 = slot3(slot5, slot6)
	slot5 = slot3
	slot3 = slot3.GetRefValue
	slot6 = "txtNameUBaseText"
	slot3 = slot3(slot5, slot6)
	slot0.btnTalenttxtNameUBaseText = slot3
	slot3 = slot0.btnEquipUButton
	slot3 = slot3.transform
	slot5 = slot3
	slot3 = slot3.GetComponent
	slot6 = "ObjectReference"
	slot3 = slot3(slot5, slot6)
	slot5 = slot3
	slot3 = slot3.GetRefValue
	slot6 = "txtNameUBaseText"
	slot3 = slot3(slot5, slot6)
	slot0.btnEquiptxtNameUBaseText = slot3
	slot3 = slot0.btnStoreUButton
	slot3 = slot3.transform
	slot5 = slot3
	slot3 = slot3.GetComponent
	slot6 = "ObjectReference"
	slot3 = slot3(slot5, slot6)
	slot5 = slot3
	slot3 = slot3.GetRefValue
	slot6 = "txtNameUBaseText"
	slot3 = slot3(slot5, slot6)
	slot0.btnStoretxtNameUBaseText = slot3
	slot3 = slot0.btnForgingUButton
	slot3 = slot3.transform
	slot5 = slot3
	slot3 = slot3.GetComponent
	slot6 = "ObjectReference"
	slot3 = slot3(slot5, slot6)
	slot5 = slot3
	slot3 = slot3.GetRefValue
	slot6 = "txtNameUBaseText"
	slot3 = slot3(slot5, slot6)
	slot0.btnForgingtxtNameUBaseText = slot3
	slot3 = slot0.btnCollectionUButton
	slot3 = slot3.transform
	slot5 = slot3
	slot3 = slot3.GetComponent
	slot6 = "ObjectReference"
	slot3 = slot3(slot5, slot6)
	slot5 = slot3
	slot3 = slot3.GetRefValue
	slot6 = "txtNameUBaseText"
	slot3 = slot3(slot5, slot6)
	slot0.btnCollectionNameUBaseText = slot3
	slot3 = slot0.btnGoToUButton
	slot3 = slot3.transform
	slot5 = slot3
	slot3 = slot3.GetComponent
	slot6 = "ObjectReference"
	slot3 = slot3(slot5, slot6)
	slot6 = slot3
	slot4 = slot3.GetRefValue
	slot7 = "chaosCost"
	slot4 = slot4(slot6, slot7)
	slot0.chaosCost = slot4
	slot6 = slot3
	slot4 = slot3.GetRefValue
	slot7 = "chaosCostIcon"
	slot4 = slot4(slot6, slot7)
	slot0.chaosCostIcon = slot4
	slot6 = slot3
	slot4 = slot3.GetRefValue
	slot7 = "chaosCostCurTicket"
	slot4 = slot4(slot6, slot7)
	slot0.chaosCostCurTicket = slot4

	return
	--- END OF BLOCK #0 ---



end

slot3.findObjects = slot4

slot4 = function(slot0)
	--- BLOCK #0 1-1, warpins: 1 ---
	return
	--- END OF BLOCK #0 ---



end

slot3.registerObjects = slot4

slot4 = function(slot0)
	--- BLOCK #0 1-1, warpins: 1 ---
	return
	--- END OF BLOCK #0 ---



end

slot3.initView = slot4

return slot3
--- END OF BLOCK #0 ---



