--- BLOCK #0 1-10, warpins: 1 ---
slot0 = {
	AFFINITY_REASON_BOTH = "both",
	AFFINITY_REASON_ATTR = "closePet",
	AFFINITY_REASON_TAG = "entityTag",
	AFFINITY_KEY = "affinityRatio",
	DEFAULT_BASE_CAPTURE_FIRST_CHECK_PROB_EXPONENT = 0.5,
	BASE_CAPTURE_RESULT_TYPE_MUST_SUCC = "must_succ",
	BASE_CAPTURE_RESULT_TYPE_STRUGGLE_FAIL = "struggle_fail",
	BASE_CAPTURE_RESULT_TYPE_STRUGGLE_SUCC = "struggle_succ",
	BASE_CAPTURE_RESULT_TYPE_DIRECT_FAIL = "direct_fail",
	BASE_CAPTURE_TIMELINE_STAGE_RESULT = "result",
	BASE_CAPTURE_TIMELINE_STAGE_STRUGGLE = "struggle",
	BASE_CAPTURE_TIMELINE_PHASE_STRUGGLE = 1,
	BASE_CAPTURE_TIMELINE_PHASE_INIT = 0,
	SETTLE_TYPE_RECYCLE = 2,
	SETTLE_TYPE_REWARD = 1,
	SETTLE_TYPE_NONE = 0,
	SESSION_STATE_SETTLED = 3,
	SESSION_STATE_HIT = 2,
	SESSION_STATE_FIRED = 1,
	SESSION_STATE_INIT = 0,
	MAX_HIT_DISTANCE = 5,
	BALL_MAX_EXIST_TIME = 60,
	MUST_SUCCESS_BALL_CFG_ID = 1003,
	HOST_CAPTURE_RESTORE_FALLBACK_DELAY = 5,
	SESSION_CLEAR_DELAY = 7,
	SESSION_LIFETIME = 20,
	MAX_CAPTURE_SESSION_COUNT = 50,
	MUST_SUCCESS_PROB_THRESHOLD = 0.999999,
	BIG_BALL_SETTLE_TIMEOUT = 22,
	BIG_BALL_AIR_TIMEOUT = 10,
	CAPTURE_BIG_BALL_RESULT_TIMELINE = 302,
	CAPTURE_BIG_BALL_STRUGGLE_TIMELINE = 301,
	CAPTURE_NORMAL_BALL_PRE_TIMELINE = 204,
	CAPTURE_NORMAL_BALL_RESULT_TIMELINE = 202,
	CAPTURE_NORMAL_BALL_STRUGGLE_TIMELINE = 203,
	CAPTURE_NORMAL_BALL_ABSORB_TIMELINE = 201
}
slot1 = math
slot1 = slot1.pi
slot1 = slot1 / 2
slot0.MAX_BEHIND_ANGLE = slot1
slot1 = {
	Normal = 1,
	Other = 3,
	Quick = 2
}
slot0.CATCH_TYPE = slot1
slot1 = {
	DEFAULT_DISTANCE = 4,
	PREF_KEY_DISTANCE = "CaptureCloseupDistance",
	PREF_KEY_ENABLE = "CaptureCloseupEnable",
	BLEND_OUT = 0.4,
	BLEND_IN = 0.5,
	FOV = 35
}
slot0.CLOSEUP_CAMERA = slot1

return slot0
--- END OF BLOCK #0 ---



