--- BLOCK #0 1-48, warpins: 1 ---
slot0 = {
	SESSION_LIFETIME = 20,
	MAX_CAPTURE_SESSION_COUNT = 50,
	MUST_SUCCESS_PROB_THRESHOLD = 0.999999,
	BIG_BALL_SETTLE_TIMEOUT = 22,
	BIG_BALL_AIR_TIMEOUT = 10,
	CAPTURE_BIG_BALL_RESULT_TIMELINE = 302,
	CAPTURE_BIG_BALL_STRUGGLE_TIMELINE = 301,
	CAPTURE_NORMAL_BALL_PRE_TIMELINE = 204,
	CAPTURE_NORMAL_BALL_LUCKY_RESULT_TIMELINE = 205,
	CAPTURE_NORMAL_BALL_RESULT_TIMELINE = 202,
	CAPTURE_NORMAL_BALL_STRUGGLE_TIMELINE = 203,
	CAPTURE_NORMAL_BALL_ABSORB_TIMELINE = 201,
	AFFINITY_REASON_BOTH = "both",
	AFFINITY_REASON_ATTR = "closePet",
	AFFINITY_REASON_TAG = "entityTag",
	AFFINITY_KEY = "affinityRatio",
	DEFAULT_BASE_CAPTURE_FIRST_CHECK_PROB_EXPONENT = 0.5,
	BASE_CAPTURE_RESULT_TYPE_MUST_SUCC = "must_succ",
	BASE_CAPTURE_RESULT_TYPE_STRUGGLE_FAIL = "struggle_fail",
	BASE_CAPTURE_RESULT_TYPE_STRUGGLE_SUCC = "struggle_succ",
	BASE_CAPTURE_RESULT_TYPE_DIRECT_FAIL = "direct_fail",
	BASE_CAPTURE_TIMELINE_STAGE_RESULT = "result",
	BASE_CAPTURE_TIMELINE_STAGE_STRUGGLE = "struggle",
	BASE_CAPTURE_TIMELINE_PHASE_STRUGGLE = 1,
	BASE_CAPTURE_TIMELINE_PHASE_INIT = 0,
	SETTLE_TYPE_RECYCLE = 2,
	SETTLE_TYPE_REWARD = 1,
	SETTLE_TYPE_NONE = 0,
	SESSION_STATE_SETTLED = 3,
	SESSION_STATE_HIT = 2,
	SESSION_STATE_FIRED = 1,
	SESSION_STATE_INIT = 0,
	MAX_HIT_DISTANCE = 5,
	BALL_MAX_EXIST_TIME = 60,
	MUST_SUCCESS_BALL_CFG_ID = 1003,
	LUCKY_CAPTURE_CLIENT_DESTROY_DELAY = 10,
	HOST_CAPTURE_RESTORE_FALLBACK_DELAY = 5,
	REWARD_MAX_QUEUE_AGE_MS = 3000,
	REWARD_MAX_PENDING_JOBS = 128,
	REWARD_SLICE_BUSY_PENDING_JOBS = 32,
	REWARD_SLICE_BUSY_BUDGET_MS = 16,
	REWARD_SLICE_BUDGET_MS = 8,
	LUCKY_SESSION_CLEAR_DELAY = 13,
	SESSION_CLEAR_DELAY = 7
}
slot1 = math
slot1 = slot1.pi
slot1 = slot1 / 2
slot0.MAX_BEHIND_ANGLE = slot1
slot1 = {
	FRAME_BALL_CONTEXT_MISMATCH = 9,
	FRAME_CONTEXT_CHANGED = 8,
	NO_VALID_PUPPET = 7,
	NO_PUPPET = 6,
	TIMEOUT = 5,
	LOSE_CLIENT = 4,
	LEAVE_SPACE = 3,
	NORMAL_MISSED = 2,
	NORMAL_RESULT = 1
}
slot0.SETTLE_REASON = slot1
slot1 = {}
slot2 = slot0.SETTLE_REASON
slot2 = slot2.LEAVE_SPACE
slot3 = true
slot1[slot2] = slot3
slot2 = slot0.SETTLE_REASON
slot2 = slot2.LOSE_CLIENT
slot3 = true
slot1[slot2] = slot3
slot2 = slot0.SETTLE_REASON
slot2 = slot2.TIMEOUT
slot3 = true
slot1[slot2] = slot3
slot2 = slot0.SETTLE_REASON
slot2 = slot2.NO_PUPPET
slot3 = true
slot1[slot2] = slot3
slot2 = slot0.SETTLE_REASON
slot2 = slot2.NO_VALID_PUPPET
slot3 = true
slot1[slot2] = slot3
slot2 = slot0.SETTLE_REASON
slot2 = slot2.FRAME_CONTEXT_CHANGED
slot3 = true
slot1[slot2] = slot3
slot2 = slot0.SETTLE_REASON
slot2 = slot2.FRAME_BALL_CONTEXT_MISMATCH
slot3 = true
slot1[slot2] = slot3
slot0.ABNORMAL_RECYCLE_SETTLE_REASON = slot1
slot1 = {
	ABNORMAL_SESSION_CLEARED = 6,
	ABNORMAL_ADD_PET_FAILED = 5,
	ABNORMAL_CALC_RESULT_FAILED = 4,
	ABNORMAL_ENTITY_MISSING = 3,
	ABNORMAL_RUNTIME_TARGET_MISSING = 2,
	FAIL = 1,
	SUCCESS = 0
}
slot0.CATCH_RESULT = slot1
slot1 = {
	LUCKY = "lucky"
}
slot0.FORCE_RESULT_REASON = slot1
slot1 = {
	Other = 3,
	Quick = 2,
	Normal = 1
}
slot0.CATCH_TYPE = slot1
slot1 = {
	PAID = 2,
	NORMAL = 1
}
slot0.BALL_BAR_TYPE = slot1
slot1 = {
	PREF_KEY_ENABLE = "CaptureCloseupEnable",
	BLEND_OUT = 0.4,
	BLEND_IN = 0.5,
	FOV = 35,
	DEFAULT_DISTANCE = 4,
	PREF_KEY_DISTANCE = "CaptureCloseupDistance"
}
slot0.CLOSEUP_CAMERA = slot1

return slot0
--- END OF BLOCK #0 ---



