--- BLOCK #0 1-116, warpins: 1 ---
slot0 = {
	is_enum_dummy = true
}
slot1 = {}
slot1.ENTITY_DESTROY = slot0
slot1.ENTITY_ADD = slot0
slot1.ENTITY_REMOVE = slot0
slot1.BALL_DRIVE_START = slot0
slot1.BALL_DRIVE_TIME = slot0
slot1.BALL_DRIVE_ADD_TIME = slot0
slot1.BALL_DRIVE_CATCH_NUM = slot0
slot1.BALL_DRIVE_MOVE = slot0
slot1.BALL_DRIVE_END = slot0
slot1.BALL_DRIVE_END_UI = slot0
slot1.BALL_DRIVE_END_IMMEDIATE = slot0
slot1.CATCH_MODE_CHANGE_UI = slot0
slot1.CHARACTER_STATE_CHANGE = slot0
slot1.LOCK_ENITY_MSG = slot0
slot1.TOPLOGO_ALERT = slot0
slot1.TOPLOGO_PERCEPT_CHANGED = slot0
slot1.TOPLOGO_CATCH_LOCK = slot0
slot1.TOPLOGO_DIALOGUE = slot0
slot1.TOPLOGO_BUBBLE = slot0
slot1.TOPLOGO_BUBBLE_WITH_INFO = slot0
slot1.TOPLOGO_PLAYER_CHAT_BUBBLE = slot0
slot1.TOPLOGO_PLAYER_CHAT_TYPING = slot0
slot1.TOPLOGO_FRIEND_INTERACT = slot0
slot1.TOPLOGO_PHOTO = slot0
slot1.TOPLOGO_TEAM_SPEECH = slot0
slot1.TOPLOGO_QUEST = slot0
slot1.TOPLOGO_PET_SHIELD = slot0
slot1.TOPLOGO_SHIELD_POINT = slot0
slot1.TOPLOGO_SHIELD_BREAK = slot0
slot1.TOPLOGO_BREAK_POINT = slot0
slot1.TOPLOGO_HEALTH_POINT = slot0
slot1.TOPLOGO_HEIGHT = slot0
slot1.TOPLOGO_TEAM_STATE = slot0
slot1.TOPLOGO_PETFERTILITY = slot0
slot1.TOPLOGO_PET_EXCHANGE = slot0
slot1.TOPLOGO_VLOG = slot0
slot1.TOPLOGO_FOCUS = slot0
slot1.ON_FREEZE_HP_CHANGED = slot0
slot1.ON_FREEZE_HP_HIT = slot0
slot1.ON_FREEZE_HP_OUT_TIME = slot0
slot1.ON_CAMOUFLAGE_CHANGE = slot0
slot1.ON_BUFF_CHANGE = slot0
slot1.BUFF_LAYER_CHANGE = slot0
slot1.ON_BUFF_ADD = slot0
slot1.ON_BUFF_REMOVE = slot0
slot1.ON_BUFF_EXPIRED_TIME_CHANGE = slot0
slot1.PLAYER_ACTION_STATE_CHANGED = slot0
slot1.NPC_SPECIAL_STATE_UPDATE = slot0
slot1.ON_MAP_MARK_TRACE_ADD = slot0
slot1.ON_MAP_MARK_TRACE_REMOVE = slot0
slot1.ON_MAP_MARK_UPDATED = slot0
slot1.ON_MAP_MARK_CHUNK_INDEX_CHANGED = slot0
slot1.ON_MAP_AREA_UNLOCK = slot0
slot1.ON_ITEM_OBTAIN_CLOSE_PANEL = slot0
slot1.ON_PET_LEVEL_UP_CLOSE_PANEL = slot0
slot1.QUEST_MARK_REFRESH = slot0
slot1.CAST_CHEM_SKILL_ON_TARGET = slot0
slot1.NPC_INTERACT_BUBBLE_GROUP = slot0
slot1.ENTITY_VISIBLE_CHANGED = slot0
slot1.ENTITY_ACTIVE_CHANGED = slot0
slot1.VIRTUAL_CHEST_UNLOCKSTART = slot0
slot1.VIRTUAL_CHEST_INTERACTRESULT = slot0
slot1.VIRTUAL_CHEST_REFRESHMODEL = slot0
slot1.VIRTUAL_CHEST_INTERACTINTERRUPT = slot0
slot1.VIRTUAL_CHEST_DESTROY = slot0
slot1.VIRTUAL_CHEST_SETVISIBLE = slot0
slot1.HOMELAND_WORK_STATE_CHANGED = slot0
slot1.HOMELAND_ACTION_STATE_CHANGED = slot0
slot1.HOMELAND_TRANSPORT_STATE_CHANGED = slot0
slot1.LIFT_BE_LIFTED = slot0
slot1.LIFT_BE_UNLIFTED = slot0
slot1.LIFTER_DEAD = slot0
slot1.ON_MAIN_PLAYER_CUSTOM_VARIABLE_CHANGED = slot0
slot1.ON_PLAYER_SWITCH_CONTROL = slot0
slot1.ON_PLAYER_SWITCH_CONTROL_ALL_CLIENT = slot0
slot1.ON_FOR_RADIUS_CHANGE = slot0
slot1.ON_TOTEM_MAP_CHANGED = slot0
slot1.PET_BALL_MAP_HATCH_SLOT_STATUS_CHANGED = slot0
slot1.ON_MAP_RELOADED = slot0
slot1.ON_LANGUAGE_CHANGED = slot0
slot1.DIALOGUE_GRAPH_ON_START = slot0
slot1.SANDBOX_PLAYER_PROPERTY_CHANGED = slot0
slot1.SANDBOX_UPDATE = slot0
slot1.APPEAR_FROM_TOPLOGO_BUFF = slot0
slot1.ECS_MAX_AMOUNT_CHANGE = slot0
slot1.PLATFORM_LOCAL_COMMUNICATION_POLICY_CHANGED = slot0
slot1.PLATFORM_NAME_MASK_POLICY_REFRESHED = slot0
slot1.PLATFORM_UGC_POLICY_CHANGED = slot0
slot1.PLATFORM_BLOCK_LIST_CHANGED = slot0
slot1.PLATFORM_FRIEND_LIST_CHANGED = slot0
slot1.FISHING_CAPTURE_SKILL_START = slot0
slot1.FISHING_CAPTURE_SKILL_END = slot0
slot1.FISHING_CAPTURE_SKILL_SHOT_END = slot0
slot1.PLATFORM_ACHIEVEMENT_PHOTO_SAVED = slot0
slot1.PLATFORM_ACHIEVEMENT_TAKE_PHOTO = slot0
slot1.PLATFORM_ACHIEVEMENT_VARIANT_TRIGGERED = slot0
slot1.PLATFORM_ACHIEVEMENT_ELITE_KILLED = slot0
slot1.PLATFORM_ACHIEVEMENT_COSTUME_DYED = slot0
slot1.PLATFORM_ACHIEVEMENT_ROGUE_PASSED = slot0
slot1.PLATFORM_ACHIEVEMENT_METEOROLOGY_EXPERIENCED = slot0
slot1.PLATFORM_ACHIEVEMENT_STAR_TITLE_CHANGED = slot0
slot1.PLATFORM_ACHIEVEMENT_RAINBOW_PET_CAUGHT = slot0
slot1.PLATFORM_ACHIEVEMENT_HUG_PET = slot0
slot1.PLATFORM_ACHIEVEMENT_HOME_CAMP_DISPATCH_FINISHED = slot0
slot1.PLATFORM_SOCIAL_ACTION_REQUEST = slot0
slot1.PLATFORM_SOCIAL_INBOUND_INVITE = slot0
slot1.PLATFORM_SHELL_INVITE_AUTO_ACCEPT = slot0
slot1.PLATFORM_CROSS_PLATFORM_SETTING_CHANGED = slot0
slot1.PLATFORM_USER_SIGNED_IN = slot0
slot1.PLATFORM_ONLINE_ID_CHANGED = slot0
slot2 = pairs
slot4 = slot1
slot2, slot3, slot4 = slot2(slot4)
--- END OF BLOCK #0 ---

UNCONDITIONAL JUMP; TARGET BLOCK #7


--- BLOCK #1 117-122, warpins: 1 ---
slot7 = string
slot7 = slot7.upper
slot9 = slot5
slot7 = slot7(slot9)
--- END OF BLOCK #1 ---

if slot7 ~= slot5 then
JUMP TO BLOCK #2
else
JUMP TO BLOCK #3
end


--- BLOCK #2 123-128, warpins: 1 ---
slot7 = error
slot9 = "attr.upper() != attr: "
slot10 = slot5
slot9 = slot9 .. slot10

slot7(slot9)

--- END OF BLOCK #2 ---

UNCONDITIONAL JUMP; TARGET BLOCK #6


--- BLOCK #3 129-133, warpins: 1 ---
slot7 = type
slot9 = slot6
slot7 = slot7(slot9)
--- END OF BLOCK #3 ---

if slot7 == "table" then
JUMP TO BLOCK #4
else
JUMP TO BLOCK #5
end


--- BLOCK #4 134-136, warpins: 1 ---
slot7 = slot6.is_enum_dummy
--- END OF BLOCK #4 ---

if slot7 ~= true then
JUMP TO BLOCK #5
else
JUMP TO BLOCK #6
end


--- BLOCK #5 137-141, warpins: 2 ---
slot7 = error
slot9 = "%s: type(v) ~= enum_dummy: "
slot10 = slot5
slot9 = slot9 .. slot10

slot7(slot9)

--- END OF BLOCK #5 ---

FLOW; TARGET BLOCK #6


--- BLOCK #6 142-142, warpins: 3 ---
slot1[slot5] = slot5

--- END OF BLOCK #6 ---

FLOW; TARGET BLOCK #7


--- BLOCK #7 143-144, warpins: 2 ---
--- END OF BLOCK #7 ---

for slot5, slot6 in slot2, slot3, slot4
LOOP BLOCK #1
GO OUT TO BLOCK #8


--- BLOCK #8 145-145, warpins: 1 ---
return slot1
--- END OF BLOCK #8 ---



