--- BLOCK #0 1-196, warpins: 1 ---
slot0 = {
	TRIGGER_TARGET_CHECK_CUSTOM_VARIABLE = 4,
	TRIGGER_TARGET_USE_ITEM = 3,
	TRIGGER_TARGET_CUSTOM_ACTION = 1,
	TRIGGER_ID_ANY = 0,
	CUSTOM_TRIGGER_NUM_POS = 5,
	CUSTOM_TRIGGER_OPERATOR_POS = 4,
	CUSTOM_TRIGGER_EXTAR_TARGET_POS = 3,
	CUSTOM_TRIGGER_TARGET_POS = 2,
	CUSTOM_TRIGGER_NAME_POS = 1,
	TRIGGER_SYSTEM_PLAYER_STATIC_GATED = 11,
	TRIGGER_SYSTEM_PLAYER_EVENT = 10,
	TRIGGER_TARGET_HOME_HAVE_FURNITURE = 237,
	TRIGGER_TARGET_HOME_FACILITY_SET_FORMULA = 238,
	TRIGGER_TARGET_HOME_FACILITY_PROGRESS = 239,
	TRIGGER_TARGET_HOME_FACILITY_OUTPUT = 240,
	TRIGGER_TARGET_IS_IN_HOME = 241,
	TRIGGER_TRAGET_ROGUE_EXCHANGE = 242,
	TRIGGER_TARGET_CORE_CARRY_NUM = 243,
	TRIGGER_TARGET_HOME_FACILITY_WORK = 244,
	TRIGGER_TARGET_SPACE_TYPE = 245,
	TRIGGER_TARGET_CATCH_FAIL_BY_BALL_LEVEL = 246,
	TRIGGER_TARGET_SPAWNER_DONE = 247,
	TRIGGER_TARGET_CONTROL_GOTO_POSITION = 248,
	TRIGGER_TARGET_CONTROL_PET_STAGE = 249,
	TRIGGER_TARGET_CONTROL_PET_LABEL = 250,
	TIRGGER_TARGET_CONTROL_PET_GROPU = 251,
	TRIGGER_TARGET_LOGIN_NUM = 252,
	TRIGGER_TARGET_QUIZ_COMPLETE = 253,
	TRIGGER_TARGET_COMBAT_ACTION_NODE_BY_FORM = 254,
	TRIGGER_TARGET_ADMISSION_DAY = 255,
	TRIGGER_TARGET_CHECK_TARGET = 256,
	TRIGGER_PET_REMAINDER_NUM = 257,
	TRIGGER_HAS_PET_RACE = 258,
	TRIGGER_PET_RACE = 259,
	TRIGGER_PET_RACE_POSITION = 260,
	TRIGGER_FINISH_BATCH_DIALOGUEID = 261,
	TRIGGER_MATCH_GAINS = 262,
	TRIGGER_TARGET_MATCH_GRABEGG = 263,
	TRIGGER_QUEST_ACCEPTED_DAY = 265,
	TRIGGER_CLOSE_INTERFACE = 268,
	TRIGGER_BOSS_FINISH_CHECK = 269,
	TRIGGER_CONTROL_GOTO_POSITION_PET = 270,
	TRIGGER_ACT_ARKCARN_PHOTE_PET = 271,
	TRIGGER_ACT_COMPLETE_VOTED = 272,
	TRIGGER_ACT_ADDED_WEBCOM = 273,
	TRIGGER_ACT_ARKCARN_PHOTO_STAGE = 274,
	TRIGGER_ACT_STAGE_OPEN = 275,
	TRIGGER_ACT_FIREWORKS = 276,
	TRIGGER_AREA_INTERNAL = 277,
	TRIGGER_ACT_LOGIN = 278,
	TRIGGER_ROBEGG_ENTER_DG = 279,
	TRIGGER_ROBEGG_OPEN_EGG = 280,
	TRIGGER_ROBEGG_ACTIVATE_DG = 281,
	TRIGGER_ROBEGG_EXIT_DG = 282,
	TRIGGER_ROBEGG_TRANS_EGG = 283,
	TRIGGER_ROBEGG_RETREAT = 284,
	TRIGGER_IN_TIME_WEATHER_BLOCK = 285,
	TRIGGER_TARGET_USE_PET_ULTIMATE_SKILL = 287,
	TRIGGER_EVOLVE_PET = 288,
	TRIGGER_ACT_TASK_ONEGROUP_FINED = 289,
	TRIGGER_ACT_TASK_ALLGROUPS_FINED = 290,
	TRIGGER_FRIEND_EXCHANGE_PET = 291,
	TRIGGER_PET_USED_POTENT_POINT_SUM = 292,
	TRIGGER_TARGET_CLIENT_BIND = 293,
	TRIGGER_TARGET_CATCH_PETGROUP_COUNT = 294,
	TRIGGER_TARGET_HOME_CAR_LEVEL = 295,
	TRIGGER_TARGET_HOME_CAR_COMP_LEVEL = 296,
	TRIGGER_TARGET_ARRIVE_HOME_CAR_POSITION = 297,
	TRIGGER_TARGET_SPECIAL_TRAIN_CHAPTER_FINISH = 298,
	TRIGGER_TARGET_LEYLINETREE_NOURISH_NUM_COUNT = 299,
	TRIGGER_TARGET_HOME_ORDER = 300,
	TRIGGER_TARGET_EGG_EVACUATE = 301,
	TRIGGER_TARGET_BOSS_SCORE = 302,
	TRIGGER_TARGET_COMPLETE_COMBAT_SIM_COUNT = 303,
	TRIGGER_TARGET_CAMP_PLACE_FURNITURE = 304,
	TRIGGER_TARGET_HOME_INCUBATOR_PLACE_EGG = 305,
	TRIGGER_TARGET_HOME_ADD_FEED = 306,
	TRIGGER_TARGET_HOME_START_DISPATCH = 307,
	HOME_SWITCH_TO_POWER_MODE = 308,
	TRIGGER_TARGET_PET_RANKUP_COUNT = 309,
	TRIGGER_TARGET_PET_RANKUP_TIMES = 310,
	TRIGGER_TARGET_APPEARNCE_COUNT_TOTAL = 311,
	TRIGGER_TARGET_EXPLORE_MAP_COVER = 312,
	TRIGGER_TARGET_ADD_RUNE_COUNT = 313,
	TRIGGER_TARGET_HAS_CORE_QUALITY_NUM = 314,
	TRIGGER_TARGET_UPGRADE_CORE_QUALITY_COUNT = 315,
	TRIGGER_TARGET_HAS_RUNE_QUALITY_NUM = 316,
	TRIGGER_TARGET_REDUCE_ENERGY_TOTAL = 317,
	TRIGGER_TARGET_REDUCE_ENERGY = 318,
	TRIGGER_TARGET_PET_UPGRADE_STAR = 319,
	TRIGGER_TARGET_OBTAIN_REWARD_TOTAL = 320,
	TRIGGER_TARGET_PLAY_BOSS_RUSH = 321,
	TRIGGER_TARGET_WIN_BOSS_RUSH = 322,
	TRIGGER_TARGET_SIMULATION_TRAIN_PASS = 323,
	TRIGGER_TARGET_SIMULATION_TRAIN_PLAY = 324,
	TRIGGER_TARGET_ROGUE_EXCHANGE_BOX = 325,
	TRIGGER_TARGET_METEOROLOGY_EXPERIENCE = 326,
	TRIGGER_TARGET_ROBEGG_RETREAT_COUNT = 328,
	TRIGGER_TARGET_ROBEGG_PLAY_COUNT = 329,
	TRIGGER_HAS_PET_ID = 330,
	TRIGGER_TARGET_OPENING_INTERFACE = 331,
	TRIGGER_TARGET_COLLECT_BADGE_STATE = 332,
	TRIGGER_TARGET_CONTROL_EGG = 333,
	TRIGGER_TARGET_SUBMITED_EGG = 334,
	TRIGGER_TARGET_MATCH_GAINS_STATE = 335,
	TRIGGER_TARGET_HOME_PLACE_FACILITY_TYPE = 336,
	TRIGGER_TARGET_OWN_CORE_CARRY_COUNT = 337,
	TRIGGER_TARGET_ACTIVATE_CORE_CARRY_EFFECT = 338,
	TRIGGER_TARGET_OBTAIN_EGG_ITEMS = 339,
	TRIGGER_TARGET_SIMULATION_TRAIN_UNLOCKED_MERITS = 340,
	TRIGGER_TARGET_GROUP_TOUR_ACTIVATE_TIMES = 341,
	TRIGGER_TARGET_GROUP_TOUR_GIFT_TIMES = 342,
	TRIGGER_TARGET_OUTFIT_COUNT_TOTAL = 343,
	TRIGGER_TARGET_EMOTE_DONE_COUNT = 344,
	TRIGGER_TARGET_EMOTE_FLUET_MEET_FRIENDS = 345,
	TRIGGER_TARGET_QUEST_TYPE_DONE = 346,
	TRIGGER_TARGET_BOSS_RUSH_RANKS = 347,
	TRIGGER_TARGET_SPECIAL_TRAIN_REQUIRED_TASK = 348,
	TRIGGER_TARGET_HOME_ORDERS_DONE = 349,
	TRIGGER_TARGET_EMOTE_TRIGGER_TIMES = 350,
	TRIGGER_TARGET_THROW_PUPPET_TYPELIMIT = 351,
	TRIGGER_TARGET_SCENE_ID_STATIC = 352,
	TRIGGER_TARGET_REPORT_CATCH_RESULTS_TOTAL = 355,
	TRIGGER_TARGET_REDUCE_MONEY_TOTAL = 356,
	TRIGGER_SYSTEM_PLAYER_BADGE = 9,
	TRIGGER_SYSTEM_BADGE = 8,
	TRIGGER_SYSTEM_ACTIVITY_TASK = 7,
	TRIGGER_SYSTEM_GAMEPLAYTARGET = 6,
	TRIGGER_SYSTEM_SOCIAL_ACTION = 5,
	TRIGGER_SYSTEM_GUIDE = 4,
	TRIGGER_SYSTEM_PET_COND = 3,
	TRIGGER_SYSTEM_PLAYER_COND = 2,
	TRIGGER_SYSTEM_PET = 1,
	TRIGGER_SYSTEM_PLAYER = 0,
	TRIGGER_STATIS_TYPE_STATIC = 2,
	TRIGGER_STATIS_TYPE_CURRENT = 1,
	TRIGGER_STATIS_TYPE_COUNT = 0,
	TRIGGER_QUEST_INDEX_END = 4,
	TRIGGER_QUEST_INDEX_START = 1,
	TRIGGER_REGTYPE_QUEST_COM_ACTION_OBJECTIVE = 4,
	TRIGGER_REGTYPE_QUEST_RUNCOND = 3,
	TRIGGER_REGTYPE_QUEST_OBJECTIVE = 2,
	TRIGGER_REGTYPE_QUEST_CLAIMCOND = 1,
	TRIGGER_REGTYPE_CUSTOM = 0,
	TRIGGER_TARGET_USE_ITEM_TOTAL = 357,
	TRIGGER_TARGET_CATCH_RAINBOW_PET = 358,
	TRIGGER_TARGET_HOME_RANDOM_PRODUCE = 359,
	TRIGGER_TARGET_SANDBOX_QUEST_EVENT = 360,
	PET_TRIGGER_TARGET_LAB = 1022,
	PET_TRIGGER_TARGET_CP_VALUE = 1021,
	PET_TRIGGER_TARGET_HAS_EXPLORE = 1020,
	PET_TRIGGER_TARGET_IS_FORM = 1019,
	PET_TRIGGER_TARGET_HAS_ELEMENT = 1018,
	PET_TRIGGER_SEND_AI_MSG_FORM = 1017,
	PET_TRIGGER_SEND_AI_MSG = 1016,
	PET_TRIGGER_SWITCH_TIME = 1015,
	PET_TRIGGER_KILL_STREAK_FORM = 1014,
	PET_TRIGGER_KILL_STREAK = 1013,
	PET_TRIGGER_TARGET_CHARACTER = 1012,
	PET_TRIGGER_CHECK_SCORE_STAGE = 1011,
	PET_TRIGGER_TARGET_COMBAT_ACTION_NODE = 1010,
	PET_TRIGGER_KILL_WITH_TEAM_FORM = 1009,
	PET_TRIGGER_KILL_WITH_TEAM = 1008,
	PET_TRIGGER_BASE_PROPERTY_LIST = 1007,
	PET_TRIGGER_CHECK_MBTI = 1006,
	PET_TRIGGER_TARGET_EVOLUTION = 1005,
	PET_TRIGGER_TARGET_EDIT_NAME = 1004,
	PET_TRIGGER_TARGET_LEVEL_MAX = 1003,
	PET_TRIGGER_TARGET_IS_EXCHANGE_PET = 1002,
	PET_TRIGGER_TARGET_LEVELUP = 1001,
	PET_TRIGGER_TARGET_LEVEL = 1000,
	PET_TRIGGER_TARGET_MIN = 1000,
	TRIGGER_TARGET_NPC_DUEL_FINISH_COUNT = 416,
	TRIGGER_TARGET_BOSS_REWARD_RECEIVE_COUNT = 415,
	TRIGGER_TARGET_GAIN_BADGE_MEDAL = 414,
	TRIGGER_TARGET_CONTROL_PET_CAN_FLY_GE = 413,
	TRIGGER_TARGET_CLASS_OPEN_DAY = 412,
	TRIGGER_TARGET_ROBEGG_TALENT_UNLOCK = 411,
	TRIGGER_TARGET_FOLLOW_CATCH_AMBER = 410,
	TRIGGER_TARGET_FOLLOW_CATCH_PET = 409,
	TRIGGER_TARGET_CATCH_PET_LEVELGAP = 408,
	TRIGGER_TARGET_LARGE_NUMBER_CHECK = 407,
	TRIGGER_TARGET_HAS_PET_UPDATE_SKILL_BY_SINGLE = 406,
	TRIGGER_TARGET_HAS_PET_UPDATE_SKILL_BY_ETHNIC = 405,
	TRIGGER_TARGET_GET_ITEMS_BYCONDITION = 404,
	TRIGGER_TARGET_NPC_DUEL_CLEAR_SHOWCOUNT_TOTAL = 403,
	TRIGGER_TARGET_AREA_CHECK = 402,
	TRIGGER_TARGET_BREAK_PET_TEMPLATE = 401,
	TRIGGER_TARGET_HAS_BADGES = 400,
	TRIGGER_TARGET_LEYLINETREE_UP_CAPTURE = 399,
	TRIGGER_TARGET_LEYLINETREE_UP_MAPBLOCK = 398,
	KILL_PET_TEMPLATE_BY_ELEMENTAL_RELATION = 397,
	TRIGGER_TARGET_TAKE_PHOTO_BY_SUBJECT_STUDIO_COUNT = 396,
	TRIGGER_TARGET_TAKE_PHOTO_BY_SUBJECT_AREA_COUNT = 395,
	TRIGGER_TARGET_PET_TEMPLATE_INDIVIDUAL_LEVELS_REACH = 394,
	TRIGGER_TARGET_PET_TEMPLATE_INDIVIDUAL_LVEVL_UP_COUNT = 393,
	TRIGGER_TARGET_ROB_EGG_LEVEL = 392,
	TRIGGER_TARGET_HAS_PLAYER_NAME = 391,
	TRIGGER_TARGET_NPC_DUEL_CLEAR = 390,
	TRIGGER_TARGET_MONTHCARD_ACTIVATED = 389,
	TRIGGER_TARGET_HAS_BADGE_BY_TYPE = 388,
	TRIGGER_TARGET_HAS_BADGE = 387,
	TRIGGER_TARGET_GET_MONEY_HOME_TOTAL = 386,
	TRIGGER_TARGET_GET_EGG_TOTAL = 385,
	TRIGGER_TARGET_PET_JEWELRY_CHANGE = 384,
	TRIGGER_TARGET_APPEARANCE_SHOW_CHANGE_PLAYER = 383,
	TRIGGER_TARGET_BP_Level = 382,
	TRIGGER_TARGET_BP_Gear = 381,
	TRIGGER_TARGET_CONTROL_PET = 380,
	TRIGGER_TARGET_PET_UPGRADE_STAR_COUNT = 379,
	TRIGGER_TARGET_ROGUE_EXCHANGE_BOX_COUNT = 378,
	TRIGGER_TARGET_GROUP_TOUR_ACTIVATE_TIMES_COUNT = 377,
	TRIGGER_TARGET_HOME_PALCE_PET_COUNT = 376,
	TRIGGER_TARGET_HOME_PLACE_FURNITURE_COUNT = 375,
	TRIGGER_TARGET_REPORT_CATCH_TOTAL_COUNT = 374,
	TRIGGER_TARGET_ROGUE_PASS_LEVEL_SEPCBAT = 373,
	TRIGGER_TARGET_KILL_LAB_PET_SEPCBAT = 372,
	TRIGGER_TARGET_KILL_PET_TEMPLATEID = 371,
	TRIGGER_TARGET_ACT_SOCRE = 370,
	TRIGGER_TARGET_EARTHTREE = 369,
	TRIGGER_TARGET_SHOP_BUYITEM = 368,
	TRIGGER_TARGET_COLLECT_ITEM = 367,
	TRIGGER_TARGET_ROBEGG_PLUND = 366,
	TRIGGER_TARGET_TAKE_PHOTO_PET = 365,
	TRIGGER_ACT_LOGIN_CONTINUE = 364,
	TRIGGER_ACT_TASK_SPEIC_TASKS_RECVED = 363,
	TRIGGER_COMPLETE_COMBAT_SIM_DIFFICULTY_COUNT = 362,
	TRIGGER_ACT_TASK_SPEIC_TASKS_FINED = 361,
	TRIGGER_TARGET_HOME_STOREHOUSE_ITEM_NUM = 236,
	TRIGGER_TARGET_PET_AI_MSG_BASE = 235,
	TRIGGER_TARGET_HOME_CLEAN_SUNDRIES_NUM = 234,
	TRIGGER_TARGET_PET_NUM_LEVEL = 233,
	TRIGGER_TARGET_ACTIVATE_SPECIFIC_MAP_MARKER = 232,
	TRIGGER_TARGET_SPECIAL_TRAIN_REPORT_TIMES = 231,
	TRIGGER_TARGET_REPORT_EXP_LEVELUP = 230,
	TRIGGER_TARGET_REPORT_NUM = 229,
	TRIGGER_TARGET_SP_POWER_FULL = 228,
	TRIGGER_TARGET_ROGUE_TALENT_TREE_NODE = 227,
	TRIGGER_TARGET_SPECIAL_TRAIN_FINISH = 226,
	TRIGGER_TARGET_LEYLINETREE_NOURISH_NUM = 225,
	TRIGGER_TARGET_RECOVER_CASTER_NUM = 224,
	TRIGGER_TARGET_PHOTO_NUM = 223,
	TRIGGER_TARGET_STOP_BURROW_BY_SKILL = 222,
	TRIGGER_TARGET_IN_TEAM = 221,
	TRIGGER_TARGET_PLAYER_RESPAWN_BONFIRE = 220,
	TRIGGER_TARGET_FRIEND_INTIMACY = 219,
	TRIGGER_TARGET_HATCH_EGG = 218,
	TRIGGER_TARGET_SIMULATION_TRAIN_LEVEL = 217,
	TRIGGER_TARGET_HOME_GROUND_UNLOCK = 216,
	TRIGGER_TARGET_HAVE_RAINBOW_PET = 215,
	TRIGGER_TARGET_HOME_PALCE_PET = 214,
	TRIGGER_TARGET_HOME_PLACE_FURNITURE = 213,
	TRIGGER_TARGET_HOME_UNLOCK = 212,
	TRIGGER_TARGET_ENTER_LEADER_SPACE = 211,
	TRIGGER_TARGET_ENTER_LINE_PHASE = 210,
	TRIGGER_TARGET_PET_BATTLE_TAG = 209,
	TRIGGER_TARGET_ATTRIBUTE_COMPARE = 208,
	TRIGGER_TARGET_CATCH_PET_BY_STATICID = 207,
	TRIGGER_TARGET_SERVER_OPEN_DAY = 206,
	TRIGGER_TARGET_KILL_PET_TEMPLATE_SPECIFIC = 205,
	TRIGGER_TARGET_GET_PET_TEMPLATE_SPECIFIC = 204,
	TRIGGER_TARGET_OPEN_CHEST_BY_TEMPLATEID = 202,
	TRIGGER_TARGET_METEOROLOGY = 201,
	TRIGGER_TARGET_WEATHER = 200,
	TRIGGER_TARGET_PET_HP_GE_PERCENT = 199,
	TRIGGER_TARGET_PET_HP_LE_PERCENT = 198,
	TRIGGER_TARGET_PLAYER_TITLE = 197,
	TRIGGER_TARGET_PLAYER_TITLE_UP = 196,
	TRIGGER_TARGET_PLAYER_IS_CONTROL_PET = 195,
	TRIGGER_TARGET_EXCHANGE_PETS_NUM = 194,
	TRIGGER_TARGET_FRIENDS_NUM = 193,
	TRIGGER_TARGET_PLAYER_RESPAWN_CAMP = 192,
	TRIGGER_TARGET_SPECIAL_PET_TYPE = 191,
	TRIGGER_TARGET_PET_HP_PERCENT = 190,
	TRIGGER_TARGET_UNHIT_COUNT = 189,
	TRIGGER_TARGET_VEHICLE_INTERACTION = 188,
	TRIGGER_TARGET_PET_TEAM_SKILL_TYPE = 187,
	TRIGGER_TARGET_SANDBOX_IN = 186,
	TRIGGER_TARGET_BACKSTAGE_TYPE_ADVANTAGE = 185,
	TRIGGER_TARGET_CUR_BALL_USE_OUT_SWITCH = 184,
	TRIGGER_TARGET_CUR_BALL_NUM_LESS_EQUAL = 183,
	TRIGGER_TARGET_CHEST_DISTANCE = 182,
	TRIGGER_TARGET_LEYLINETREE_CAN_LEVELUP = 181,
	TRIGGER_TARGET_IN_COMBAT = 180,
	TRIGGER_TARGET_PET_HP_PERCENT_TIME = 179,
	TRIGGER_TARGET_TARGET_MINUS_TEAM_AVG_LEVEL = 178,
	TRIGGER_TARGET_MAX_MINUS_TEAM_AVG_LEVEL = 177,
	TRIGGER_TARGET_PET_KILL_PET_OR_PUPPET = 176,
	TRIGGER_TARGET_CATCH_FAIL = 175,
	TRIGGER_TARGET_FUNCTION_UNLOCK = 174,
	TRIGGER_TARGET_SCENE_ID = 173,
	TRIGGER_TARGET_PLAYER_HP_PERCENT = 172,
	TRIGGER_TARGET_PET_DIE_COUNT_IN_STATE = 171,
	TRIGGER_TARGET_REPORT_COLLECT_SCORE = 170,
	TRIGGER_TARGET_USE_PET_SPECIAL_SKILL = 169,
	TRIGGER_TARGET_PET_EVOLVE = 168,
	TRIGGER_TARGET_CATCH_COUNT_NUM = 167,
	TRIGGER_TARGET_KNOWN_PET_NUM = 166,
	TRIGGER_TARGET_JOINED_VOICE_CHANNEL = 165,
	TRIGGER_TARGET_CREAT_TEAM_VOICE_CHANNEL = 164,
	TRIGGER_TARGET_CATCH_PET_BUFF = 163,
	TRIGGER_TARGET_CATCH_PET_STATE = 162,
	TRIGGER_TARGET_GET_PET_WEIGHT = 161,
	TRIGGER_TARGET_PET_CHEMICAL_REACTIONS = 160,
	TRIGGER_TARGET_KILL_PUPPET_BY_ELEMENT = 159,
	TRIGGER_TARGET_PET_KILL_ELEMENT = 158,
	TRIGGER_TARGET_PET_HIT_ELEMENT_BY_ELEMENT = 157,
	TRIGGER_TARGET_SANDBOX_SIGNAL_ID = 156,
	TRIGGER_TARGET_CHEST_REACH_IMPULSE_THRESHOLD = 155,
	TRIGGER_TARGET_COMPLETE_COMBAT_SIM = 154,
	TRIGGER_TARGET_STUN_ON_COLLISION = 153,
	TRIGGER_TARGET_CATCH_PET_SCORE_COUNT = 152,
	TRIGGER_TARGET_PET_RARE_SKILL_COUNT = 151,
	TRIGGER_TARGET_DUNGEON_PASS_CNT = 150,
	TRIGGER_TARGET_DUNGEON_PASS = 149,
	TRIGGER_TARGET_LEYLINETREE_POINT = 147,
	TRIGGER_TARGET_IN_CAMOU = 146,
	TRIGGER_TARGET_HAVE_BUFF = 145,
	TRIGGER_TARGET_CAMOU_DETECTED = 144,
	TRIGGER_TARGET_PLAYER_BODY_TYPE = 143,
	TRIGGER_TARGET_ADD_BUFF = 142,
	TRIGGER_TARGET_KILL_CREATION = 141,
	TRIGGER_TARGET_COMBAT_ACTION_NODE = 140,
	TRIGGER_TARGET_PET_CHARACTER_SPECIAL = 139,
	TRIGGER_TARGET_FRIEND_PVP_COUNT = 138,
	TRIGGER_TARGET_PVP_COUNT = 137,
	TRIGGER_TARGET_TOTEM_LEVEL = 136,
	TRIGGER_TARGET_LEYLINETREE_LEVEL = 135,
	TRIGGER_TARGET_PET_ATTR_COUNT = 133,
	TRIGGER_TARGET_PET_SCORE_COUNT = 132,
	TRIGGER_TARGET_EGG_ATTR_COUNT = 131,
	TRIGGER_TARGET_PET_HATCH_COUNT = 130,
	TRIGGER_TARGET_SHOP_BUY = 129,
	TRIGGER_TARGET_APPEARNCE_COUNT = 128,
	TRIGGER_TARGET_SKILL_LEARN_COUNT = 127,
	TRIGGER_TARGET_SKILL_HIT_ENEMY = 126,
	TRIGGER_TARGET_HAVE_SPECIAL_TRAIN_BADGE_REWARD = 123,
	TRIGGER_TARGET_PET_AI_MSG = 122,
	TRIGGER_TARGET_FINISH_ALL_SPECIAL_TRAIN_TASK = 121,
	TRIGGER_TARGET_GAIN_SPECIAL_TRAIN_BADGE = 120,
	TRIGGER_TARGET_FINISH_SPECIAL_TRAIN_TYPE_TASK = 119,
	TRIGGER_TARGET_TWIN_PET_CHOICE = 118,
	TRIGGER_TARGET_LEYLINETREE_ACTIVE = 117,
	TRIGGER_TARGET_COMPLETE_COURSE = 116,
	TRIGGER_TARGET_LEVELITEM_STATE = 115,
	TRIGGER_TARGET_TIME_STATE = 114,
	TRIGGER_TARGET_SANDBOX_SUCCESS = 113,
	TRIGGER_TARGET_CHECK_CLIENT_CUSTOM_VARIABLE = 112,
	TRIGGER_TARGET_ENTER_SCENE = 111,
	TRIGGER_TARGET_CHECK_NPC_BEHAVIOR_STATUS = 110,
	TRIGGER_TARGET_READ_CONTENT = 109,
	TRIGGER_TARGET_ACTIVITY_PHASE = 107,
	TRIGGER_TARGET_DISTANCE_PLAYER_NPC_CALLFRIEND = 106,
	TRIGGER_TARGET_ETHNICGROUP_JUDGMENT = 105,
	TRIGGER_TARGET_UNLOCK_DIALOGUE_GRAPH = 104,
	TRIGGER_TARGET_CALL_FRIEND = 103,
	TRIGGER_TARGET_THROW_PUPPET = 102,
	TRIGGER_TARGET_SANDBOX_PHASE = 101,
	TRIGGER_TARGET_FINISH_GUIDE = 100,
	TRIGGER_TARGET_PLAYER_IN_BEHAVIOR = 99,
	TRIGGER_TARGET_PLAYER_BEHAVIOR = 98,
	TRIGGER_TARGET_PET_TRAIT_UNLOCK = 97,
	TRIGGER_TARGET_COMPLETE_POI_NUM = 96,
	TRIGGER_TARGET_PET_CONSUME = 95,
	TRIGGER_TARGET_ITEM_CONSUME = 94,
	TRIGGER_TARGET_TAKE_PHOTO = 93,
	TRIGGER_TARGET_GUIDE_COURSE = 92,
	TRIGGER_TARGET_INTERACT = 91,
	TRIGGER_TARGET_ATTRIBUTE_KILL_PUPPET = 90,
	TRIGGER_TARGET_CONTROL_BEHAVIOR = 89,
	TRIGGER_TARGET_MEET_PET = 88,
	TRIGGER_TARGET_CATCH_GENDER = 87,
	TRIGGER_TARGET_COMBAT_COOPERATE = 85,
	TRIGGER_TARGET_PET_SKILL_UNLOCK = 82,
	TRIGGER_TARGET_PET_FEATURE_UNLOCK = 81,
	TRIGGER_TARGET_NEAR_PET = 79,
	TRIGGER_TARGET_ANGLE_OF_VIEW = 78,
	TRIGGER_TARGET_STATE_COMBAT = 77,
	TRIGGER_TARGET_RECEIVE_REWARD = 76,
	TRIGGER_TARGET_FAIL_RESTRAINED = 75,
	TRIGGER_TARGET_BREAK_STATE = 74,
	TRIGGER_TARGET_PET_POWER_FULL = 73,
	TRIGGER_TARGET_OFFLINE_TIME = 72,
	TRIGGER_TARGET_TIMEOUT_POI = 71,
	TRIGGER_TARGET_FAIL_POI = 70,
	TRIGGER_TARGET_CONTROL_PET_TYPE = 68,
	TRIGGER_TARGET_PET_LEVEL_TEMPLATE_HISTORY = 67,
	TRIGGER_TARGET_COMPLETE_QUESTGROUP_NUM = 66,
	TRIGGER_TARGET_COMPLETE_QUEST_NUM = 65,
	TRIGGER_TARGET_OPEN_CHEST_BY_STATICID = 64,
	TRIGGER_TARGET_HAS_ITEMS = 63,
	TRIGGER_TARGET_USE_PLAYER_SKILL_TREE = 62,
	TRIGGER_TARGET_QUEST_STATE = 61,
	TRIGGER_TARGET_QUESTGROUP_STATE = 60,
	TRIGGER_TARGET_CONTROL_PET_TMPL = 59,
	TRIGGER_TARGET_CONTROL_PET_FIRST = 58,
	TRIGGER_TARGET_USE_SKILLPOINT = 56,
	TRIGGER_TARGET_REDUCE_MONEY = 55,
	TRIGGER_TARGET_UNLOCKED_MAP_MARK = 54,
	TRIGGER_TARGET_HAS_ITEM_TMPL = 53,
	TRIGGER_TARGET_GETITEM_BY_STYPE = 52,
	TRIGGER_TARGET_PET_TMPL_LEVELUP = 51,
	TRIGGER_TARGET_PETBALL_CHANGEPET = 50,
	TRIGGER_TARGET_PET_PROP_STRENGTHENPOINT = 49,
	TRIGGER_TARGET_PET_PROP_CP = 48,
	TRIGGER_TARGET_PET_TMPL_NUM_LEVEL = 47,
	TRIGGER_TARGET_PET_TMPL_SKILL_NUM = 46,
	TRIGGER_TARGET_GET_PET_TMPL_BY_EVOLVE = 45,
	TRIGGER_TARGET_UNLOCK_DIALOGUEID = 44,
	TRIGGER_TARGET_CATCH_BY_CASTERID = 43,
	TRIGGER_TARGET_USE_PLAYER_SKILL = 42,
	TRIGGER_TARGET_USE_CHAIN_SKILL_KILL_PUPPET = 41,
	TRIGGER_TARGET_CATCH_PET_ELEMENT = 40,
	TRIGGER_TARGET_KILL_PUPPET_BY_PET_COMBAT = 39,
	TRIGGER_TARGET_USE_PET_SKILL = 38,
	TRIGGER_TARGET_USE_EXPLORE_SKILL = 37,
	TRIGGER_TARGET_CHAIN_ATTACK = 36,
	TRIGGER_TARGET_COLLECT_PET_AVATAR = 35,
	TRIGGER_TARGET_USE_ITEM_BY_STYPE = 34,
	TRIGGER_TARGET_GET_PET_TEMPLATE_IN_BREAK = 33,
	TRIGGER_TARGET_GET_PET_TEMPLATE_FROM_BEHIND = 32,
	TRIGGER_TARGET_GOTO_POSITION = 30,
	TRIGGER_TARGET_SPAWNER_DEATH = 29,
	TRIGGER_TARGET_CATCH_COUNT_ONCE = 27,
	TRIGGER_TARGET_CLEAN_MONSTER_CAMP = 26,
	TRIGGER_TARGET_OPEN_INTERFACE = 24,
	TRIGGER_TARGET_REPORT_CATCH_RESULTS = 23,
	TRIGGER_TARGET_FREE_PET = 22,
	TRIGGER_TARGET_LARGE_NUMBER_CATCH = 21,
	TRIGGER_TARGET_LEARN_SKILL_BY_HAND = 19,
	TRIGGER_TARGET_TOTAL_RESEARCH_LEVEL = 18,
	TRIGGER_TARGET_GET_ITEMS = 17,
	TRIGGER_TARGET_POSSESSION_KILL_MONSTER = 16,
	TRIGGER_TARGET_SEPARATE_KILL_MONSTER = 15,
	TRIGGER_TARGET_PLAYER_LEVEL = 14,
	TRIGGER_TARGET_CATCH_COUNT = 13,
	TRIGGER_TARGET_OPEN_CHEST = 12,
	TRIGGER_TARGET_COLLECT_PET_NUM = 11,
	TRIGGER_TARGET_RESEARCH_PROGRESS = 10,
	TRIGGER_TARGET_KILL_PET_TEMPLATE = 9,
	TRIGGER_TARGET_PET_LEVEL_TEMPLATE = 8,
	TRIGGER_TARGET_GET_PET_TEMPLATE = 7,
	TRIGGER_TARGET_RESEARCH_COMPLETE_PET = 6,
	TRIGGER_TARGET_POS_SPHERE = 5
}
slot1 = {}
slot2 = slot0.TRIGGER_SYSTEM_PET
slot3 = true
slot1[slot2] = slot3
slot2 = slot0.TRIGGER_SYSTEM_PET_COND
slot3 = true
slot1[slot2] = slot3
slot0.IS_PET_CONDTION = slot1
slot1 = {}
slot2 = slot0.TRIGGER_SYSTEM_PLAYER
slot3 = true
slot1[slot2] = slot3
slot2 = slot0.TRIGGER_SYSTEM_PLAYER_COND
slot3 = true
slot1[slot2] = slot3
slot2 = slot0.TRIGGER_SYSTEM_SOCIAL_ACTION
slot3 = true
slot1[slot2] = slot3
slot2 = slot0.TRIGGER_SYSTEM_GAMEPLAYTARGET
slot3 = true
slot1[slot2] = slot3
slot2 = slot0.TRIGGER_SYSTEM_PLAYER_BADGE
slot3 = true
slot1[slot2] = slot3
slot2 = slot0.TRIGGER_SYSTEM_PLAYER_STATIC_GATED
slot3 = true
slot1[slot2] = slot3
slot0.DEFAULT_REGISTER_TRIGGER_PLAYER = slot1
slot1 = {}
slot2 = slot0.TRIGGER_SYSTEM_PET
slot3 = true
slot1[slot2] = slot3
slot2 = slot0.TRIGGER_SYSTEM_PET_COND
slot3 = true
slot1[slot2] = slot3
slot0.DEFAULT_REGISTER_TRIGGER_PET = slot1
slot1 = {}
slot2 = slot0.TRIGGER_SYSTEM_PLAYER_COND
slot3 = true
slot1[slot2] = slot3
slot2 = slot0.TRIGGER_SYSTEM_PET_COND
slot3 = true
slot1[slot2] = slot3
slot0.ONLY_CHECKING_TRIGGER = slot1

slot1 = function(slot0)
	--- BLOCK #0 1-5, warpins: 1 ---
	slot1 = TriggerConst
	slot1 = slot1.DEFAULT_REGISTER_TRIGGER_PLAYER
	slot1 = slot1[slot0]
	--- END OF BLOCK #0 ---

	slot1 = if not slot1 then
	JUMP TO BLOCK #1
	else
	JUMP TO BLOCK #3
	end


	--- BLOCK #1 6-10, warpins: 1 ---
	slot1 = TriggerConst
	slot1 = slot1.DEFAULT_REGISTER_TRIGGER_PET
	slot1 = slot1[slot0]
	--- END OF BLOCK #1 ---

	slot1 = if not slot1 then
	JUMP TO BLOCK #2
	else
	JUMP TO BLOCK #3
	end


	--- BLOCK #2 11-13, warpins: 1 ---
	slot1 = TriggerConst
	slot1 = slot1.ONLY_CHECKING_TRIGGER
	slot1 = slot1[slot0]

	--- END OF BLOCK #2 ---

	FLOW; TARGET BLOCK #3


	--- BLOCK #3 14-14, warpins: 3 ---
	return slot1
	--- END OF BLOCK #3 ---



end

slot0.isDefaultRegisterUseType = slot1
slot1 = {}
slot2 = slot0.TRIGGER_TARGET_GOTO_POSITION
slot3 = true
slot1[slot2] = slot3
slot2 = slot0.TRIGGER_TARGET_ANGLE_OF_VIEW
slot3 = true
slot1[slot2] = slot3
slot2 = slot0.TRIGGER_TARGET_NEAR_PET
slot3 = true
slot1[slot2] = slot3
slot2 = slot0.TRIGGER_TARGET_MEET_PET
slot3 = true
slot1[slot2] = slot3
slot2 = slot0.TRIGGER_TARGET_CONTROL_BEHAVIOR
slot3 = true
slot1[slot2] = slot3
slot2 = slot0.TRIGGER_TARGET_PLAYER_BEHAVIOR
slot3 = true
slot1[slot2] = slot3
slot2 = slot0.TRIGGER_TARGET_DISTANCE_PLAYER_NPC_CALLFRIEND
slot3 = true
slot1[slot2] = slot3
slot2 = slot0.TRIGGER_TARGET_OPEN_INTERFACE
slot3 = true
slot1[slot2] = slot3
slot2 = slot0.TRIGGER_TARGET_PET_AI_MSG
slot3 = true
slot1[slot2] = slot3
slot2 = slot0.TRIGGER_TARGET_PET_AI_MSG_BASE
slot3 = true
slot1[slot2] = slot3
slot2 = slot0.TRIGGER_TARGET_CAMOU_DETECTED
slot3 = true
slot1[slot2] = slot3
slot2 = slot0.TRIGGER_TARGET_READ_CONTENT
slot3 = true
slot1[slot2] = slot3
slot2 = slot0.TRIGGER_TARGET_CHEST_REACH_IMPULSE_THRESHOLD
slot3 = true
slot1[slot2] = slot3
slot2 = slot0.TRIGGER_TARGET_PET_CHEMICAL_REACTIONS
slot3 = true
slot1[slot2] = slot3
slot2 = slot0.TRIGGER_TARGET_PET_HP_LE_PERCENT
slot3 = true
slot1[slot2] = slot3
slot2 = slot0.TRIGGER_TARGET_PET_HP_GE_PERCENT
slot3 = true
slot1[slot2] = slot3
slot2 = slot0.TRIGGER_TARGET_PET_HP_PERCENT_TIME
slot3 = true
slot1[slot2] = slot3
slot2 = slot0.TRIGGER_TARGET_PET_HP_PERCENT
slot3 = true
slot1[slot2] = slot3
slot2 = slot0.TRIGGER_TARGET_CHEST_DISTANCE
slot3 = true
slot1[slot2] = slot3
slot2 = slot0.TRIGGER_TARGET_UNHIT_COUNT
slot3 = true
slot1[slot2] = slot3
slot2 = slot0.TRIGGER_TARGET_PET_TEAM_SKILL_TYPE
slot3 = true
slot1[slot2] = slot3
slot2 = slot0.TRIGGER_TARGET_FRIENDS_NUM
slot3 = true
slot1[slot2] = slot3
slot2 = slot0.TRIGGER_TARGET_ATTRIBUTE_COMPARE
slot3 = true
slot1[slot2] = slot3
slot2 = slot0.TRIGGER_TARGET_SPACE_TYPE
slot3 = true
slot1[slot2] = slot3
slot2 = slot0.TRIGGER_TARGET_SP_POWER_FULL
slot3 = true
slot1[slot2] = slot3
slot2 = slot0.TRIGGER_TARGET_CONTROL_GOTO_POSITION
slot3 = true
slot1[slot2] = slot3
slot2 = slot0.TRIGGER_PET_RACE_POSITION
slot3 = true
slot1[slot2] = slot3
slot2 = slot0.TRIGGER_CLOSE_INTERFACE
slot3 = true
slot1[slot2] = slot3
slot2 = slot0.TRIGGER_CONTROL_GOTO_POSITION_PET
slot3 = true
slot1[slot2] = slot3
slot2 = slot0.TRIGGER_IN_TIME_WEATHER_BLOCK
slot3 = true
slot1[slot2] = slot3
slot2 = slot0.TRIGGER_TARGET_ARRIVE_HOME_CAR_POSITION
slot3 = true
slot1[slot2] = slot3
slot2 = slot0.TRIGGER_TARGET_OPENING_INTERFACE
slot3 = true
slot1[slot2] = slot3
slot2 = slot0.TRIGGER_TARGET_CATCH_PET_LEVELGAP
slot3 = true
slot1[slot2] = slot3
slot0.CLIENT_TRIGGER_TARGET = slot1
slot1 = {}
slot2 = slot0.TRIGGER_TARGET_GOTO_POSITION
slot1.TRIGGER_TARGET_GOTO_POSITION = slot2
slot2 = slot0.TRIGGER_TARGET_ANGLE_OF_VIEW
slot1.TRIGGER_TARGET_ANGLE_OF_VIEW = slot2
slot2 = slot0.TRIGGER_TARGET_NEAR_PET
slot1.TRIGGER_TARGET_NEAR_PET = slot2
slot2 = slot0.TRIGGER_TARGET_MEET_PET
slot1.TRIGGER_TARGET_MEET_PET = slot2
slot2 = slot0.TRIGGER_TARGET_CONTROL_BEHAVIOR
slot1.TRIGGER_TARGET_CONTROL_BEHAVIOR = slot2
slot2 = slot0.TRIGGER_TARGET_PLAYER_BEHAVIOR
slot1.TRIGGER_TARGET_PLAYER_BEHAVIOR = slot2
slot2 = slot0.TRIGGER_TARGET_DISTANCE_PLAYER_NPC_CALLFRIEND
slot1.TRIGGER_TARGET_DISTANCE_PLAYER_NPC_CALLFRIEND = slot2
slot2 = slot0.TRIGGER_TARGET_OPEN_INTERFACE
slot1.TRIGGER_TARGET_OPEN_INTERFACE = slot2
slot2 = slot0.TRIGGER_TARGET_PET_AI_MSG
slot1.TRIGGER_TARGET_PET_AI_MSG = slot2
slot2 = slot0.TRIGGER_TARGET_PET_AI_MSG_BASE
slot1.TRIGGER_TARGET_PET_AI_MSG_BASE = slot2
slot2 = slot0.TRIGGER_TARGET_CAMOU_DETECTED
slot1.TRIGGER_TARGET_CAMOU_DETECTED = slot2
slot2 = slot0.TRIGGER_TARGET_READ_CONTENT
slot1.TRIGGER_TARGET_READ_CONTENT = slot2
slot2 = slot0.TRIGGER_TARGET_CHEST_REACH_IMPULSE_THRESHOLD
slot1.TRIGGER_TARGET_CHEST_REACH_IMPULSE_THRESHOLD = slot2
slot2 = slot0.TRIGGER_TARGET_SP_POWER_FULL
slot1.TRIGGER_TARGET_SP_POWER_FULL = slot2
slot2 = slot0.TRIGGER_CLOSE_INTERFACE
slot1.TRIGGER_CLOSE_INTERFACE = slot2
slot2 = slot0.TRIGGER_TARGET_OPENING_INTERFACE
slot1.TRIGGER_TARGET_OPENING_INTERFACE = slot2
slot2 = slot0.TRIGGER_TARGET_CATCH_PET_LEVELGAP
slot1.TRIGGER_TARGET_CATCH_PET_LEVELGAP = slot2
slot0.EDITOR_CLIENT_TRIGGER_TARGET = slot1

slot1 = function(slot0, slot1)
	--- BLOCK #0 1-3, warpins: 1 ---
	slot2 = slot0 * 10
	slot2 = slot2 + slot1

	return slot2
	--- END OF BLOCK #0 ---



end

slot0.genCustomTriggerKey = slot1

slot1 = function(slot0)
	--- BLOCK #0 1-5, warpins: 1 ---
	slot1 = slot0 % 10
	slot2 = slot0 - slot1
	slot2 = slot2 / 10
	slot3 = slot1

	return slot2, slot3
	--- END OF BLOCK #0 ---



end

slot0.parseCustomTriggerKey = slot1

slot1 = function(slot0, slot1)
	--- BLOCK #0 1-2, warpins: 1 ---
	--- END OF BLOCK #0 ---

	slot1 = if not slot1 then
	JUMP TO BLOCK #1
	else
	JUMP TO BLOCK #2
	end


	--- BLOCK #1 3-6, warpins: 1 ---
	slot2 = require
	slot4 = "Data.trigger_data"
	slot2 = slot2(slot4)
	slot1 = slot2
	--- END OF BLOCK #1 ---

	FLOW; TARGET BLOCK #2


	--- BLOCK #2 7-8, warpins: 2 ---
	--- END OF BLOCK #2 ---

	slot2 = if slot1 then
	JUMP TO BLOCK #3
	else
	JUMP TO BLOCK #4
	end


	--- BLOCK #3 9-12, warpins: 1 ---
	slot2 = TriggerConst
	slot2 = slot2.CUSTOM_TRIGGER_NAME_POS
	slot2 = slot0[slot2]
	slot2 = slot1[slot2]

	--- END OF BLOCK #3 ---

	FLOW; TARGET BLOCK #4


	--- BLOCK #4 13-14, warpins: 2 ---
	--- END OF BLOCK #4 ---

	if slot2 == nil then
	JUMP TO BLOCK #5
	else
	JUMP TO BLOCK #6
	end


	--- BLOCK #5 15-15, warpins: 1 ---
	return

	--- END OF BLOCK #5 ---

	FLOW; TARGET BLOCK #6


	--- BLOCK #6 16-21, warpins: 2 ---
	slot3 = slot2.trigger
	slot4 = TriggerConst
	slot4 = slot4.CUSTOM_TRIGGER_TARGET_POS
	slot4 = slot0[slot4]
	--- END OF BLOCK #6 ---

	slot4 = if not slot4 then
	JUMP TO BLOCK #7
	else
	JUMP TO BLOCK #8
	end


	--- BLOCK #7 22-22, warpins: 1 ---
	slot4 = 0
	--- END OF BLOCK #7 ---

	FLOW; TARGET BLOCK #8


	--- BLOCK #8 23-27, warpins: 2 ---
	slot5 = TriggerConst
	slot5 = slot5.CUSTOM_TRIGGER_EXTAR_TARGET_POS
	slot5 = slot0[slot5]
	slot6 = slot2.statsType

	return slot3, slot4, slot5, slot6
	--- END OF BLOCK #8 ---



end

slot0.getTriggerInfo = slot1
slot1 = {
	CONTINUOUS = 2,
	IN_TIME_LIMIT_COUNT = 1,
	IN_TIME_CON_COUNT = 3
}
slot0.TIME_STATISTICS_TYPE = slot1
slot1 = {
	HOUR = 2,
	MINUTES = 1,
	SECONDS = 4,
	DAY = 3
}
slot0.TIME_STATISTICS_TIMEUNIT = slot1

return slot0
--- END OF BLOCK #0 ---



