--- BLOCK #0 1-18, warpins: 1 ---
slot0 = require
slot2 = "Core.Framework.Class"
slot0 = slot0(slot2)
slot1 = require
slot3 = "Guis.UIView"
slot1 = slot1(slot3)
slot2 = slot0.LightClass
slot4 = "ChatView"
slot5 = slot1
slot2 = slot2(slot4, slot5)

slot3 = function(slot0)
	--- BLOCK #0 1-571, warpins: 1 ---
	slot1 = slot0.transform
	slot3 = slot1
	slot1 = slot1.GetComponent
	slot4 = "ObjectReference"
	slot1 = slot1(slot3, slot4)
	slot0.objectReference = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "bgCloseUButton"
	slot1 = slot1(slot3, slot4)
	slot0.bgCloseUButton = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "rootUComponent"
	slot1 = slot1(slot3, slot4)
	slot0.rootUComponent = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "btnChatUButton"
	slot1 = slot1(slot3, slot4)
	slot0.btnChatUButton = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "btnNoticeUButton"
	slot1 = slot1(slot3, slot4)
	slot0.btnNoticeUButton = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "btnPublicUButton"
	slot1 = slot1(slot3, slot4)
	slot0.btnPublicUButton = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "btnSetUButton"
	slot1 = slot1(slot3, slot4)
	slot0.btnSetUButton = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "privateUComponent"
	slot1 = slot1(slot3, slot4)
	slot0.privateUComponent = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "personalUComponent"
	slot1 = slot1(slot3, slot4)
	slot0.personalUComponent = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "publicUComponent"
	slot1 = slot1(slot3, slot4)
	slot0.publicUComponent = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "channelListUList"
	slot1 = slot1(slot3, slot4)
	slot0.channelListUList = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "btnAddUButton"
	slot1 = slot1(slot3, slot4)
	slot0.btnAddUButton = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "btnExpendUButton"
	slot1 = slot1(slot3, slot4)
	slot0.btnExpendUButton = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "bottomSendUComponent"
	slot1 = slot1(slot3, slot4)
	slot0.bottomSendUComponent = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "btnNewUButton"
	slot1 = slot1(slot3, slot4)
	slot0.btnNewUButton = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "btnSwitchUButton"
	slot1 = slot1(slot3, slot4)
	slot0.btnSwitchUButton = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "btnVoiceUButton"
	slot1 = slot1(slot3, slot4)
	slot0.btnVoiceUButton = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "inputFieldUTMPInputField"
	slot1 = slot1(slot3, slot4)
	slot0.inputFieldUTMPInputField = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "btnSendAddUButton"
	slot1 = slot1(slot3, slot4)
	slot0.btnSendAddUButton = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "btnConfirmUButton"
	slot1 = slot1(slot3, slot4)
	slot0.btnConfirmUButton = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "addPanelUWidget"
	slot1 = slot1(slot3, slot4)
	slot0.addPanelUWidget = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "extendFuncList"
	slot1 = slot1(slot3, slot4)
	slot0.extendFuncList = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "txtDisUBaseText"
	slot1 = slot1(slot3, slot4)
	slot0.txtDisUBaseText = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "warningTipsUWidget"
	slot1 = slot1(slot3, slot4)
	slot0.warningTipsUWidget = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "btnPrivateAddUButton"
	slot1 = slot1(slot3, slot4)
	slot0.btnPrivateAddUButton = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "iconPrivateAddUImage"
	slot1 = slot1(slot3, slot4)
	slot0.iconPrivateAddUImage = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "txtPrivateEmptyUBaseText"
	slot1 = slot1(slot3, slot4)
	slot0.txtPrivateEmptyUBaseText = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "iconEmptyUImage"
	slot1 = slot1(slot3, slot4)
	slot0.iconEmptyUImage = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "txtEmptyUBaseText"
	slot1 = slot1(slot3, slot4)
	slot0.txtEmptyUBaseText = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "imgFigureUImage"
	slot1 = slot1(slot3, slot4)
	slot0.imgFigureUImage = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "channelNameUText"
	slot1 = slot1(slot3, slot4)
	slot0.channelNameUText = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "chatBoxTopAddBtn"
	slot1 = slot1(slot3, slot4)
	slot0.chatBoxTopAddBtn = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "btnPrivateOtherUButton"
	slot1 = slot1(slot3, slot4)
	slot0.btnPrivateOtherUButton = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "listOtherUList"
	slot1 = slot1(slot3, slot4)
	slot0.listOtherUList = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "personalTxtName"
	slot1 = slot1(slot3, slot4)
	slot0.personalTxtName = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "listMembersUList"
	slot1 = slot1(slot3, slot4)
	slot0.listMembersUList = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "personalTopAddBtn"
	slot1 = slot1(slot3, slot4)
	slot0.personalTopAddBtn = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "publicTxtName"
	slot1 = slot1(slot3, slot4)
	slot0.publicTxtName = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "btnPublicOtherUButton"
	slot1 = slot1(slot3, slot4)
	slot0.btnPublicOtherUButton = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "btnPublicOtherUList"
	slot1 = slot1(slot3, slot4)
	slot0.btnPublicOtherUList = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "txtSettingsUBaseText"
	slot1 = slot1(slot3, slot4)
	slot0.txtSettingsUBaseText = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "settingListUList"
	slot1 = slot1(slot3, slot4)
	slot0.settingListUList = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "chatUInputField"
	slot1 = slot1(slot3, slot4)
	slot0.chatUInputField = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "btnBottomAddUButton"
	slot1 = slot1(slot3, slot4)
	slot0.btnBottomAddUButton = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "btnCloseUButton"
	slot1 = slot1(slot3, slot4)
	slot0.btnCloseUButton = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "panelUComponent"
	slot1 = slot1(slot3, slot4)
	slot0.panelUComponent = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "noMessageRectTransform"
	slot1 = slot1(slot3, slot4)
	slot0.noMessageRectTransform = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "topInfoRectTransform"
	slot1 = slot1(slot3, slot4)
	slot0.topInfoRectTransform = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "otherPanelRectTransform"
	slot1 = slot1(slot3, slot4)
	slot0.otherPanelRectTransform = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "txtNumUBaseText"
	slot1 = slot1(slot3, slot4)
	slot0.txtNumUBaseText = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "secondTabRectTransform"
	slot1 = slot1(slot3, slot4)
	slot0.secondTabRectTransform = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "imgLikabilityUImage"
	slot1 = slot1(slot3, slot4)
	slot0.imgLikabilityUImage = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "txtNameChangeUSDFText"
	slot1 = slot1(slot3, slot4)
	slot0.txtNameChangeUSDFText = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "nameCoverUSDFText"
	slot1 = slot1(slot3, slot4)
	slot0.nameCoverUSDFText = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "addBtnCloseUButton"
	slot1 = slot1(slot3, slot4)
	slot0.addBtnCloseUButton = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "otherBtnCloseUButton"
	slot1 = slot1(slot3, slot4)
	slot0.otherBtnCloseUButton = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "messageListUList"
	slot1 = slot1(slot3, slot4)
	slot0.messageListUList = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "textAreaRectTransform"
	slot1 = slot1(slot3, slot4)
	slot0.textAreaRectTransform = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "btnMailUButton"
	slot1 = slot1(slot3, slot4)
	slot0.btnMailUButton = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "mailUComponent"
	slot1 = slot1(slot3, slot4)
	slot0.mailUComponent = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "btnGoUButton"
	slot1 = slot1(slot3, slot4)
	slot0.btnGoUButton = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "historyInformationUComponent"
	slot1 = slot1(slot3, slot4)
	slot0.historyInformationUComponent = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "settingUComponent"
	slot1 = slot1(slot3, slot4)
	slot0.settingUComponent = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "chatItemUComponent"
	slot1 = slot1(slot3, slot4)
	slot0.chatItemUComponent = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "petShareUComponent"
	slot1 = slot1(slot3, slot4)
	slot0.petShareUComponent = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "friendListPanelUComponent"
	slot1 = slot1(slot3, slot4)
	slot0.friendListPanelUComponent = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "gameplayUComponent"
	slot1 = slot1(slot3, slot4)
	slot0.gameplayUComponent = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "btnReplyUButton"
	slot1 = slot1(slot3, slot4)
	slot0.btnReplyUButton = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "replyTextUSDFText"
	slot1 = slot1(slot3, slot4)
	slot0.replyTextUSDFText = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "btnBottomEmojiUButton"
	slot1 = slot1(slot3, slot4)
	slot0.btnBottomEmojiUButton = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "emojiUWidget"
	slot1 = slot1(slot3, slot4)
	slot0.emojiUWidget = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "listEmojiUList"
	slot1 = slot1(slot3, slot4)
	slot0.listEmojiUList = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "replyUWidget"
	slot1 = slot1(slot3, slot4)
	slot0.replyUWidget = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "playerStateUSDFText"
	slot1 = slot1(slot3, slot4)
	slot0.playerStateUSDFText = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "channelPanelUComponent"
	slot1 = slot1(slot3, slot4)
	slot0.channelPanelUComponent = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "channelTipUWidget"
	slot1 = slot1(slot3, slot4)
	slot0.channelTipUWidget = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "textTipsUSDFText"
	slot1 = slot1(slot3, slot4)
	slot0.textTipsUSDFText = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "btnSystemCheckUButton"
	slot1 = slot1(slot3, slot4)
	slot0.btnSystemCheckUButton = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "bottomSearchUTMPInputField"
	slot1 = slot1(slot3, slot4)
	slot0.bottomSearchUTMPInputField = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "expendNumUSDFText"
	slot1 = slot1(slot3, slot4)
	slot0.expendNumUSDFText = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "btnFriendUButton"
	slot1 = slot1(slot3, slot4)
	slot0.btnFriendUButton = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "topOtherBtnCloseUButton"
	slot1 = slot1(slot3, slot4)
	slot0.topOtherBtnCloseUButton = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "emojiCloseUButton"
	slot1 = slot1(slot3, slot4)
	slot0.emojiCloseUButton = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "extensionCloseUButton"
	slot1 = slot1(slot3, slot4)
	slot0.extensionCloseUButton = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "btnGoTextUSDFText"
	slot1 = slot1(slot3, slot4)
	slot0.btnGoTextUSDFText = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "listFriendChannelUList"
	slot1 = slot1(slot3, slot4)
	slot0.listFriendChannelUList = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "friendUComponent"
	slot1 = slot1(slot3, slot4)
	slot0.friendUComponent = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "listEmojiTabUList"
	slot1 = slot1(slot3, slot4)
	slot0.listEmojiTabUList = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "searchPlaceHolderUSDFText"
	slot1 = slot1(slot3, slot4)
	slot0.searchPlaceHolderUSDFText = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "voicePanelUWidget"
	slot1 = slot1(slot3, slot4)
	slot0.voicePanelUWidget = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "btnVoicePlayUButton"
	slot1 = slot1(slot3, slot4)
	slot0.btnVoicePlayUButton = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "btnVoiceNotUButton"
	slot1 = slot1(slot3, slot4)
	slot0.btnVoiceNotUButton = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "textVoiceUSDFText"
	slot1 = slot1(slot3, slot4)
	slot0.textVoiceUSDFText = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "mainConsoleBarTransform"
	slot1 = slot1(slot3, slot4)
	slot0.mainConsoleBarTransform = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "textSystemCheckUSDFText"
	slot1 = slot1(slot3, slot4)
	slot0.textSystemCheckUSDFText = slot1

	return
	--- END OF BLOCK #0 ---



end

slot2.findObjects = slot3

slot3 = function(slot0)
	--- BLOCK #0 1-1, warpins: 1 ---
	return
	--- END OF BLOCK #0 ---



end

slot2.registerObjects = slot3

slot3 = function(slot0)
	--- BLOCK #0 1-1, warpins: 1 ---
	return
	--- END OF BLOCK #0 ---



end

slot2.initView = slot3

return slot2
--- END OF BLOCK #0 ---



