--- BLOCK #0 1-21, warpins: 1 ---
slot0 = require
slot2 = "Core.Framework.Class"
slot0 = slot0(slot2)
slot1 = require
slot3 = "Guis.UIView"
slot1 = slot1(slot3)
slot2 = require
slot4 = "Utils.ClientTextUtils"
slot2 = slot2(slot4)
slot3 = slot0.LightClass
slot5 = "ChatView"
slot6 = slot1
slot3 = slot3(slot5, slot6)

slot4 = function(slot0)
	--- BLOCK #0 1-501, warpins: 1 ---
	slot1 = slot0.transform
	slot3 = slot1
	slot1 = slot1.GetComponent
	slot4 = "ObjectReference"
	slot1 = slot1(slot3, slot4)
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "bgCloseUButton"
	slot2 = slot2(slot4, slot5)
	slot0.bgCloseUButton = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "rootUComponent"
	slot2 = slot2(slot4, slot5)
	slot0.rootUComponent = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "btnChatUButton"
	slot2 = slot2(slot4, slot5)
	slot0.btnChatUButton = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "btnNoticeUButton"
	slot2 = slot2(slot4, slot5)
	slot0.btnNoticeUButton = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "btnPublicUButton"
	slot2 = slot2(slot4, slot5)
	slot0.btnPublicUButton = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "btnSetUButton"
	slot2 = slot2(slot4, slot5)
	slot0.btnSetUButton = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "privateUComponent"
	slot2 = slot2(slot4, slot5)
	slot0.privateUComponent = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "personalUComponent"
	slot2 = slot2(slot4, slot5)
	slot0.personalUComponent = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "publicUComponent"
	slot2 = slot2(slot4, slot5)
	slot0.publicUComponent = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "channelListUList"
	slot2 = slot2(slot4, slot5)
	slot0.channelListUList = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "btnAddUButton"
	slot2 = slot2(slot4, slot5)
	slot0.btnAddUButton = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "btnExpendUButton"
	slot2 = slot2(slot4, slot5)
	slot0.btnExpendUButton = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "bottomSendUComponent"
	slot2 = slot2(slot4, slot5)
	slot0.bottomSendUComponent = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "btnNewUButton"
	slot2 = slot2(slot4, slot5)
	slot0.btnNewUButton = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "btnSwitchUButton"
	slot2 = slot2(slot4, slot5)
	slot0.btnSwitchUButton = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "btnVoiceUButton"
	slot2 = slot2(slot4, slot5)
	slot0.btnVoiceUButton = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "inputFieldUTMPInputField"
	slot2 = slot2(slot4, slot5)
	slot0.inputFieldUTMPInputField = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "btnSendAddUButton"
	slot2 = slot2(slot4, slot5)
	slot0.btnSendAddUButton = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "btnConfirmUButton"
	slot2 = slot2(slot4, slot5)
	slot0.btnConfirmUButton = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "addPanelUWidget"
	slot2 = slot2(slot4, slot5)
	slot0.addPanelUWidget = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "extendFuncList"
	slot2 = slot2(slot4, slot5)
	slot0.extendFuncList = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "txtDisUBaseText"
	slot2 = slot2(slot4, slot5)
	slot0.txtDisUBaseText = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "warningTipsUWidget"
	slot2 = slot2(slot4, slot5)
	slot0.warningTipsUWidget = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "btnPrivateAddUButton"
	slot2 = slot2(slot4, slot5)
	slot0.btnPrivateAddUButton = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "iconPrivateAddUImage"
	slot2 = slot2(slot4, slot5)
	slot0.iconPrivateAddUImage = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "txtPrivateEmptyUBaseText"
	slot2 = slot2(slot4, slot5)
	slot0.txtPrivateEmptyUBaseText = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "iconEmptyUImage"
	slot2 = slot2(slot4, slot5)
	slot0.iconEmptyUImage = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "txtEmptyUBaseText"
	slot2 = slot2(slot4, slot5)
	slot0.txtEmptyUBaseText = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "imgFigureUImage"
	slot2 = slot2(slot4, slot5)
	slot0.imgFigureUImage = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "channelNameUText"
	slot2 = slot2(slot4, slot5)
	slot0.channelNameUText = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "chatBoxTopAddBtn"
	slot2 = slot2(slot4, slot5)
	slot0.chatBoxTopAddBtn = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "btnPrivateOtherUButton"
	slot2 = slot2(slot4, slot5)
	slot0.btnPrivateOtherUButton = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "listOtherUList"
	slot2 = slot2(slot4, slot5)
	slot0.listOtherUList = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "personalTxtName"
	slot2 = slot2(slot4, slot5)
	slot0.personalTxtName = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "listMembersUList"
	slot2 = slot2(slot4, slot5)
	slot0.listMembersUList = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "personalTopAddBtn"
	slot2 = slot2(slot4, slot5)
	slot0.personalTopAddBtn = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "publicTxtName"
	slot2 = slot2(slot4, slot5)
	slot0.publicTxtName = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "btnPublicOtherUButton"
	slot2 = slot2(slot4, slot5)
	slot0.btnPublicOtherUButton = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "btnPublicOtherUList"
	slot2 = slot2(slot4, slot5)
	slot0.btnPublicOtherUList = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "txtSettingsUBaseText"
	slot2 = slot2(slot4, slot5)
	slot0.txtSettingsUBaseText = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "settingListUList"
	slot2 = slot2(slot4, slot5)
	slot0.settingListUList = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "chatUInputField"
	slot2 = slot2(slot4, slot5)
	slot0.chatUInputField = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "btnBottomAddUButton"
	slot2 = slot2(slot4, slot5)
	slot0.btnBottomAddUButton = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "btnCloseUButton"
	slot2 = slot2(slot4, slot5)
	slot0.btnCloseUButton = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "panelUComponent"
	slot2 = slot2(slot4, slot5)
	slot0.panelUComponent = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "noMessageRectTransform"
	slot2 = slot2(slot4, slot5)
	slot0.noMessageRectTransform = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "topInfoRectTransform"
	slot2 = slot2(slot4, slot5)
	slot0.topInfoRectTransform = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "otherPanelRectTransform"
	slot2 = slot2(slot4, slot5)
	slot0.otherPanelRectTransform = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "txtNumUBaseText"
	slot2 = slot2(slot4, slot5)
	slot0.txtNumUBaseText = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "secondTabRectTransform"
	slot2 = slot2(slot4, slot5)
	slot0.secondTabRectTransform = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "emblemUImage"
	slot2 = slot2(slot4, slot5)
	slot0.emblemUImage = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "imgLikabilityUImage"
	slot2 = slot2(slot4, slot5)
	slot0.imgLikabilityUImage = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "txtNameChangeUSDFText"
	slot2 = slot2(slot4, slot5)
	slot0.txtNameChangeUSDFText = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "nameCoverUSDFText"
	slot2 = slot2(slot4, slot5)
	slot0.nameCoverUSDFText = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "addBtnCloseUButton"
	slot2 = slot2(slot4, slot5)
	slot0.addBtnCloseUButton = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "otherBtnCloseUButton"
	slot2 = slot2(slot4, slot5)
	slot0.otherBtnCloseUButton = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "messageListUList"
	slot2 = slot2(slot4, slot5)
	slot0.messageListUList = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "textAreaRectTransform"
	slot2 = slot2(slot4, slot5)
	slot0.textAreaRectTransform = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "btnMailUButton"
	slot2 = slot2(slot4, slot5)
	slot0.btnMailUButton = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "mailUComponent"
	slot2 = slot2(slot4, slot5)
	slot0.mailUComponent = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "btnGoUButton"
	slot2 = slot2(slot4, slot5)
	slot0.btnGoUButton = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "historyInformationUComponent"
	slot2 = slot2(slot4, slot5)
	slot0.historyInformationUComponent = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "settingUComponent"
	slot2 = slot2(slot4, slot5)
	slot0.settingUComponent = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "chatItemUComponent"
	slot2 = slot2(slot4, slot5)
	slot0.chatItemUComponent = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "petShareUComponent"
	slot2 = slot2(slot4, slot5)
	slot0.petShareUComponent = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "friendListPanelUComponent"
	slot2 = slot2(slot4, slot5)
	slot0.friendListPanelUComponent = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "gameplayUComponent"
	slot2 = slot2(slot4, slot5)
	slot0.gameplayUComponent = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "btnReplyUButton"
	slot2 = slot2(slot4, slot5)
	slot0.btnReplyUButton = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "replyTextUSDFText"
	slot2 = slot2(slot4, slot5)
	slot0.replyTextUSDFText = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "btnBottomEmojiUButton"
	slot2 = slot2(slot4, slot5)
	slot0.btnBottomEmojiUButton = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "emojiUWidget"
	slot2 = slot2(slot4, slot5)
	slot0.emojiUWidget = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "listEmojiUList"
	slot2 = slot2(slot4, slot5)
	slot0.listEmojiUList = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "replyUWidget"
	slot2 = slot2(slot4, slot5)
	slot0.replyUWidget = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "playerStateUSDFText"
	slot2 = slot2(slot4, slot5)
	slot0.playerStateUSDFText = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "channelPanelUComponent"
	slot2 = slot2(slot4, slot5)
	slot0.channelPanelUComponent = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "channelTipUWidget"
	slot2 = slot2(slot4, slot5)
	slot0.channelTipUWidget = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "textTipsUSDFText"
	slot2 = slot2(slot4, slot5)
	slot0.textTipsUSDFText = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "btnSystemCheckUButton"
	slot2 = slot2(slot4, slot5)
	slot0.btnSystemCheckUButton = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "bottomSearchUTMPInputField"
	slot2 = slot2(slot4, slot5)
	slot0.bottomSearchUTMPInputField = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "expendNumUSDFText"
	slot2 = slot2(slot4, slot5)
	slot0.expendNumUSDFText = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "btnFriendUButton"
	slot2 = slot2(slot4, slot5)
	slot0.btnFriendUButton = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "topOtherBtnCloseUButton"
	slot2 = slot2(slot4, slot5)
	slot0.topOtherBtnCloseUButton = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "emojiCloseUButton"
	slot2 = slot2(slot4, slot5)
	slot0.emojiCloseUButton = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "extensionCloseUButton"
	slot2 = slot2(slot4, slot5)
	slot0.extensionCloseUButton = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "btnGoTextUSDFText"
	slot2 = slot2(slot4, slot5)
	slot0.btnGoTextUSDFText = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "listFriendChannelUList"
	slot2 = slot2(slot4, slot5)
	slot0.listFriendChannelUList = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "friendUComponent"
	slot2 = slot2(slot4, slot5)
	slot0.friendUComponent = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "listEmojiTabUList"
	slot2 = slot2(slot4, slot5)
	slot0.listEmojiTabUList = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "searchPlaceHolderUSDFText"
	slot2 = slot2(slot4, slot5)
	slot0.searchPlaceHolderUSDFText = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "voicePanelUWidget"
	slot2 = slot2(slot4, slot5)
	slot0.voicePanelUWidget = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "btnVoicePlayUButton"
	slot2 = slot2(slot4, slot5)
	slot0.btnVoicePlayUButton = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "btnVoiceNotUButton"
	slot2 = slot2(slot4, slot5)
	slot0.btnVoiceNotUButton = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "textVoiceUSDFText"
	slot2 = slot2(slot4, slot5)
	slot0.textVoiceUSDFText = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "mainConsoleBarTransform"
	slot2 = slot2(slot4, slot5)
	slot0.mainConsoleBarTransform = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "textSystemCheckUSDFText"
	slot2 = slot2(slot4, slot5)
	slot0.textSystemCheckUSDFText = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "chatInformUWidget"
	slot2 = slot2(slot4, slot5)
	slot0.chatInformUWidget = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "chatInputHolderUSDFText"
	slot2 = slot2(slot4, slot5)
	slot0.chatInputHolderUSDFText = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "btnImgLikabilityUButton"
	slot2 = slot2(slot4, slot5)
	slot0.btnImgLikabilityUButton = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "txtNewMsgUSDFText"
	slot2 = slot2(slot4, slot5)
	slot0.txtNewMsgUSDFText = slot2

	return
	--- END OF BLOCK #0 ---



end

slot3.findObjects = slot4

slot4 = function(slot0)
	--- BLOCK #0 1-1, warpins: 1 ---
	return
	--- END OF BLOCK #0 ---



end

slot3.registerObjects = slot4

slot4 = function(slot0)
	--- BLOCK #0 1-9, warpins: 1 ---
	slot1 = ClientTextUtils
	slot1 = slot1.setText
	slot3 = slot0.chatInputHolderUSDFText
	slot4 = pg
	slot4 = slot4.getGameString
	slot6 = "CHAT_TIP_INPUT"
	MULTRES = slot4(slot6)

	slot1(slot3, MULTRES)

	return
	--- END OF BLOCK #0 ---



end

slot3.initView = slot4

return slot3
--- END OF BLOCK #0 ---



