--- BLOCK #0 1-14, warpins: 1 ---
slot0 = require
slot2 = "Guis.UIView"
slot0 = slot0(slot2)
slot1 = require
slot3 = "Core.Framework.Class"
slot1 = slot1(slot3)
slot2 = slot1.LightClass
slot4 = "PetManagementView"
slot5 = slot0
slot2 = slot2(slot4, slot5)

slot3 = function(slot0)
	--- BLOCK #0 1-589, warpins: 1 ---
	slot1 = slot0.transform
	slot3 = slot1
	slot1 = slot1.GetComponent
	slot4 = "ObjectReference"
	slot1 = slot1(slot3, slot4)
	slot0.objectReference = slot1
	slot1 = slot0.transform
	slot3 = slot1
	slot1 = slot1.Find
	slot4 = "Bg/BgBlur"
	slot1 = slot1(slot3, slot4)
	slot0.blurTransform = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "root"
	slot1 = slot1(slot3, slot4)
	slot0.root = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "animation"
	slot1 = slot1(slot3, slot4)
	slot0.animation = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "closeBtn"
	slot1 = slot1(slot3, slot4)
	slot0.closeBtn = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "boxPetFilterList"
	slot1 = slot1(slot3, slot4)
	slot0.boxPetFilterList = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "fightPetList"
	slot1 = slot1(slot3, slot4)
	slot0.fightPetList = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "boxSelector"
	slot1 = slot1(slot3, slot4)
	slot0.boxSelector = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "btnLeftUButton"
	slot1 = slot1(slot3, slot4)
	slot0.btnLeftUButton = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "btnRightUButton"
	slot1 = slot1(slot3, slot4)
	slot0.btnRightUButton = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "dragReleaseUWidget"
	slot1 = slot1(slot3, slot4)
	slot0.dragReleaseUWidget = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "showFightPage"
	slot1 = slot1(slot3, slot4)
	slot0.showFightPage = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "leftPanelUComponent"
	slot1 = slot1(slot3, slot4)
	slot0.leftPanelUComponent = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "groupSelector"
	slot1 = slot1(slot3, slot4)
	slot0.groupSelector = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "fightBtnCtrl"
	slot1 = slot1(slot3, slot4)
	slot0.fightBtnCtrl = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "fightBtn"
	slot1 = slot1(slot3, slot4)
	slot0.fightBtn = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "boxList"
	slot1 = slot1(slot3, slot4)
	slot0.boxList = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "boxTidyUp"
	slot1 = slot1(slot3, slot4)
	slot0.boxTidyUp = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "btnReleaseUButton"
	slot1 = slot1(slot3, slot4)
	slot0.btnReleaseUButton = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "btnCloseUButton"
	slot1 = slot1(slot3, slot4)
	slot0.btnCloseUButton = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "startReleaseBtn"
	slot1 = slot1(slot3, slot4)
	slot0.startReleaseBtn = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "btnFilterUButton"
	slot1 = slot1(slot3, slot4)
	slot0.btnFilterUButton = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "btnFilter1UButton"
	slot1 = slot1(slot3, slot4)
	slot0.btnFilter1UButton = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "btnCleanFilterUButton"
	slot1 = slot1(slot3, slot4)
	slot0.btnCleanFilterUButton = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "midPanelUComponent"
	slot1 = slot1(slot3, slot4)
	slot0.midPanelUComponent = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "rightPanelUComponent"
	slot1 = slot1(slot3, slot4)
	slot0.rightPanelUComponent = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "btnEvolutionUButton"
	slot1 = slot1(slot3, slot4)
	slot0.btnEvolutionUButton = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "btnCultivateUButton"
	slot1 = slot1(slot3, slot4)
	slot0.btnCultivateUButton = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "btnLvUp"
	slot1 = slot1(slot3, slot4)
	slot0.btnLvUp = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "btnStudyUButton"
	slot1 = slot1(slot3, slot4)
	slot0.btnStudyUButton = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "pageUpBtnUButton"
	slot1 = slot1(slot3, slot4)
	slot0.pageUpBtnUButton = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "pageDownBtnUButton"
	slot1 = slot1(slot3, slot4)
	slot0.pageDownBtnUButton = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "maskButtonForFightUButton"
	slot1 = slot1(slot3, slot4)
	slot0.maskButtonForFightUButton = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "listCharUList"
	slot1 = slot1(slot3, slot4)
	slot0.listCharUList = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "pvpUList"
	slot1 = slot1(slot3, slot4)
	slot0.pvpUList = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "consoleKeyUList"
	slot1 = slot1(slot3, slot4)
	slot0.consoleKeyUList = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "prevPageConsoleUList"
	slot1 = slot1(slot3, slot4)
	slot0.prevPageConsoleUList = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "nextPageConsoleUList"
	slot1 = slot1(slot3, slot4)
	slot0.nextPageConsoleUList = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "cleanFilterConsole"
	slot1 = slot1(slot3, slot4)
	slot0.cleanFilterConsole = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "consoleKeyFilterUButton"
	slot1 = slot1(slot3, slot4)
	slot0.consoleKeyFilterUButton = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "pbReleaseUWidget"
	slot1 = slot1(slot3, slot4)
	slot0.pbReleaseUWidget = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "maskButtonForExploreUButton"
	slot1 = slot1(slot3, slot4)
	slot0.maskButtonForExploreUButton = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "dragAreaUButton"
	slot1 = slot1(slot3, slot4)
	slot0.dragAreaUButton = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "rogueSelectPetUButton"
	slot1 = slot1(slot3, slot4)
	slot0.rogueSelectPetUButton = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "showExplorePage"
	slot1 = slot1(slot3, slot4)
	slot0.showExplorePage = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "normalFilterParent"
	slot1 = slot1(slot3, slot4)
	slot0.normalFilterParent = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "batchReleaseFilterParent"
	slot1 = slot1(slot3, slot4)
	slot0.batchReleaseFilterParent = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "pbFilterRectTransform"
	slot1 = slot1(slot3, slot4)
	slot0.pbFilterRectTransform = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "pbFilter2RectTransform"
	slot1 = slot1(slot3, slot4)
	slot0.pbFilter2RectTransform = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "boxPetNewList"
	slot1 = slot1(slot3, slot4)
	slot0.boxPetNewList = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "boxSelPanelAnimation"
	slot1 = slot1(slot3, slot4)
	slot0.boxSelPanelAnimation = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "btnCarry"
	slot1 = slot1(slot3, slot4)
	slot0.btnCarry = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "bgBlurUWidget"
	slot1 = slot1(slot3, slot4)
	slot0.bgBlurUWidget = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "bgBlurUIBlurEffect"
	slot1 = slot1(slot3, slot4)
	slot0.bgBlurUIBlurEffect = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "listSupportUList"
	slot1 = slot1(slot3, slot4)
	slot0.listSupportUList = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "topRightTabUList"
	slot1 = slot1(slot3, slot4)
	slot0.topRightTabUList = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "selectorHotKeyContent"
	slot1 = slot1(slot3, slot4)
	slot0.selectorHotKeyContent = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "barLHotKeyContent"
	slot1 = slot1(slot3, slot4)
	slot0.barLHotKeyContent = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "barRHotKeyContent"
	slot1 = slot1(slot3, slot4)
	slot0.barRHotKeyContent = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "lockingHotKeyContent"
	slot1 = slot1(slot3, slot4)
	slot0.lockingHotKeyContent = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "leftHotKeyContent"
	slot1 = slot1(slot3, slot4)
	slot0.leftHotKeyContent = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "rightHotKeyContent"
	slot1 = slot1(slot3, slot4)
	slot0.rightHotKeyContent = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "levelUpHotKeyContent"
	slot1 = slot1(slot3, slot4)
	slot0.levelUpHotKeyContent = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "cultivateHotKeyContent"
	slot1 = slot1(slot3, slot4)
	slot0.cultivateHotKeyContent = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "carryHotKeyContent"
	slot1 = slot1(slot3, slot4)
	slot0.carryHotKeyContent = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "skillHotKeyContent"
	slot1 = slot1(slot3, slot4)
	slot0.skillHotKeyContent = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "dressHotKeyContent"
	slot1 = slot1(slot3, slot4)
	slot0.dressHotKeyContent = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "changeFormHotKeyContent"
	slot1 = slot1(slot3, slot4)
	slot0.changeFormHotKeyContent = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "filterHotKeyContent"
	slot1 = slot1(slot3, slot4)
	slot0.filterHotKeyContent = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "releaseHotKeyContent"
	slot1 = slot1(slot3, slot4)
	slot0.releaseHotKeyContent = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "bottomSelectorHotKeyContent"
	slot1 = slot1(slot3, slot4)
	slot0.bottomSelectorHotKeyContent = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "boxHotKeyContent"
	slot1 = slot1(slot3, slot4)
	slot0.boxHotKeyContent = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "fightHotKeyContent"
	slot1 = slot1(slot3, slot4)
	slot0.fightHotKeyContent = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "listBoxUList"
	slot1 = slot1(slot3, slot4)
	slot0.listBoxUList = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "topSliderUButton"
	slot1 = slot1(slot3, slot4)
	slot0.topSliderUButton = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "botSliderUButton"
	slot1 = slot1(slot3, slot4)
	slot0.botSliderUButton = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "topAlterSliderUButton"
	slot1 = slot1(slot3, slot4)
	slot0.topAlterSliderUButton = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "botAlterSliderUButton"
	slot1 = slot1(slot3, slot4)
	slot0.botAlterSliderUButton = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "btnBoxUButton"
	slot1 = slot1(slot3, slot4)
	slot0.btnBoxUButton = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "btnInfoUButton"
	slot1 = slot1(slot3, slot4)
	slot0.btnInfoUButton = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "txtSelectedUSDFText"
	slot1 = slot1(slot3, slot4)
	slot0.txtSelectedUSDFText = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "btnBox2UButton"
	slot1 = slot1(slot3, slot4)
	slot0.btnBox2UButton = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "btnDisplayUButton"
	slot1 = slot1(slot3, slot4)
	slot0.btnDisplayUButton = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "btnViewUButton"
	slot1 = slot1(slot3, slot4)
	slot0.btnViewUButton = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "btnView2UButton"
	slot1 = slot1(slot3, slot4)
	slot0.btnView2UButton = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "txtNumUSDFText"
	slot1 = slot1(slot3, slot4)
	slot0.txtNumUSDFText = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "safeBoxMobileUWidget"
	slot1 = slot1(slot3, slot4)
	slot0.animationWidget = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "consoleBarTransform"
	slot1 = slot1(slot3, slot4)
	slot0.consoleBarTransform = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "btnEvoImgArrowUImage"
	slot1 = slot1(slot3, slot4)
	slot0.btnEvoImgArrowUImage = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "roomTowerTitleUContainer"
	slot1 = slot1(slot3, slot4)
	slot0.roomTowerTitleUContainer = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "listTowerUList"
	slot1 = slot1(slot3, slot4)
	slot0.listTowerUList = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "roomTitleBossUContainer"
	slot1 = slot1(slot3, slot4)
	slot0.roomTitleBossUContainer = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "autoFilterBtnUContainer"
	slot1 = slot1(slot3, slot4)
	slot0.autoFilterBtnUContainer = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "recommendUContainer"
	slot1 = slot1(slot3, slot4)
	slot0.recommendUContainer = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "tipInfoUWidget"
	slot1 = slot1(slot3, slot4)
	slot0.tipInfoUWidget = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "tabBarUWidget"
	slot1 = slot1(slot3, slot4)
	slot0.tabBarUWidget = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "gamepadVirtualButtonUButton"
	slot1 = slot1(slot3, slot4)
	slot0.gamepadVirtualButtonUButton = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "petListUWidget"
	slot1 = slot1(slot3, slot4)
	slot0.petListUWidget = slot1

	return
	--- END OF BLOCK #0 ---



end

slot2.findObjects = slot3

return slot2
--- END OF BLOCK #0 ---



