--- BLOCK #0 1-14, warpins: 1 ---
slot0 = require
slot2 = "Core.Framework.Class"
slot0 = slot0(slot2)
slot1 = require
slot3 = "Guis.UIView"
slot1 = slot1(slot3)
slot2 = slot0.LightClass
slot4 = "HomelandFurnitureStoreView"
slot5 = slot1
slot2 = slot2(slot4, slot5)

slot3 = function(slot0)
	--- BLOCK #0 1-205, warpins: 1 ---
	slot1 = slot0.transform
	slot3 = slot1
	slot1 = slot1.GetComponent
	slot4 = "ObjectReference"
	slot1 = slot1(slot3, slot4)
	slot0.objectReference = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "bottomUComponent"
	slot1 = slot1(slot3, slot4)
	slot0.bottomUComponent = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "leftUComponent"
	slot1 = slot1(slot3, slot4)
	slot0.leftUComponent = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "rightUComponent"
	slot1 = slot1(slot3, slot4)
	slot0.rightUComponent = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "textNameUSDFText"
	slot1 = slot1(slot3, slot4)
	slot0.textNameUSDFText = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "textDescriptionUSDFText"
	slot1 = slot1(slot3, slot4)
	slot0.textDescriptionUSDFText = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "textOwnUSDFText"
	slot1 = slot1(slot3, slot4)
	slot0.textOwnUSDFText = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "textMaxUSDFText"
	slot1 = slot1(slot3, slot4)
	slot0.textMaxUSDFText = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "btnBuyUButton"
	slot1 = slot1(slot3, slot4)
	slot0.btnBuyUButton = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "btnBackUButton"
	slot1 = slot1(slot3, slot4)
	slot0.btnBackUButton = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "numSelectorUNumSelector"
	slot1 = slot1(slot3, slot4)
	slot0.numSelectorUNumSelector = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "textCostUSDFText"
	slot1 = slot1(slot3, slot4)
	slot0.textCostUSDFText = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "unlockDescUSDFText"
	slot1 = slot1(slot3, slot4)
	slot0.unlockDescUSDFText = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "listCurrencyUList"
	slot1 = slot1(slot3, slot4)
	slot0.listCurrencyUList = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "lockUSDFText"
	slot1 = slot1(slot3, slot4)
	slot0.lockUSDFText = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "redeemListUList"
	slot1 = slot1(slot3, slot4)
	slot0.redeemListUList = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "redeemUNumSelector"
	slot1 = slot1(slot3, slot4)
	slot0.redeemUNumSelector = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "btnRedeemUButton"
	slot1 = slot1(slot3, slot4)
	slot0.btnRedeemUButton = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "sourceList"
	slot1 = slot1(slot3, slot4)
	slot0.sourceList = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "drawingNameUSDFText"
	slot1 = slot1(slot3, slot4)
	slot0.drawingNameUSDFText = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "drawingSourceListUList"
	slot1 = slot1(slot3, slot4)
	slot0.drawingSourceListUList = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "drawingSourceTitleUWidget"
	slot1 = slot1(slot3, slot4)
	slot0.drawingSourceTitleUWidget = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "TextTitleGetUSDFText"
	slot1 = slot1(slot3, slot4)
	slot0.TextTitleGetUSDFText = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "modelURawImage"
	slot1 = slot1(slot3, slot4)
	slot0.modelURawImage = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "buyRedeemUComponent"
	slot1 = slot1(slot3, slot4)
	slot0.buyRedeemUComponent = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "emptySoldOutUComponent"
	slot1 = slot1(slot3, slot4)
	slot0.emptySoldOutUComponent = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "sourceUWidget"
	slot1 = slot1(slot3, slot4)
	slot0.sourceUWidget = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "btnFavoriteUButton"
	slot1 = slot1(slot3, slot4)
	slot0.btnFavoriteUButton = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "scrollRectDescUScrollRect"
	slot1 = slot1(slot3, slot4)
	slot0.scrollRectDescUScrollRect = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "btnTipsUSDFText"
	slot1 = slot1(slot3, slot4)
	slot0.btnTipsUSDFText = slot1
	slot1 = slot0.scrollRectDescUScrollRect
	slot1 = slot1.content
	slot1 = slot1.transform
	slot3 = slot1
	slot1 = slot1.GetComponent
	slot4 = "ObjectReference"
	slot1 = slot1(slot3, slot4)
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "txtDescUSDFText"
	slot2 = slot2(slot4, slot5)
	slot0.txtDescUSDFText = slot2
	slot2 = slot0.objectReference
	slot4 = slot2
	slot2 = slot2.GetRefValue
	slot5 = "txtLoadNumUSDFText"
	slot2 = slot2(slot4, slot5)
	slot0.txtLoadNumUSDFText = slot2
	slot2 = slot0.objectReference
	slot4 = slot2
	slot2 = slot2.GetRefValue
	slot5 = "txtLiveNumUSDFText"
	slot2 = slot2(slot4, slot5)
	slot0.txtLiveNumUSDFText = slot2

	return
	--- END OF BLOCK #0 ---



end

slot2.findObjects = slot3

return slot2
--- END OF BLOCK #0 ---



