--- BLOCK #0 1-20, warpins: 1 ---
slot0 = require
slot2 = "Core.Log.LoggerManager"
slot0 = slot0(slot2)
slot0 = slot0.getLogger
slot2 = "InteractSecondView"
slot0 = slot0(slot2)
slot1 = require
slot3 = "Core.Framework.Class"
slot1 = slot1(slot3)
slot2 = require
slot4 = "Guis.UIView"
slot2 = slot2(slot4)
slot3 = slot1.LightClass
slot5 = "HomelandPlacementView"
slot6 = slot2
slot3 = slot3(slot5, slot6)

slot4 = function(slot0)
	--- BLOCK #0 1-191, warpins: 1 ---
	slot1 = slot0.transform
	slot3 = slot1
	slot1 = slot1.GetComponent
	slot4 = "ObjectReference"
	slot1 = slot1(slot3, slot4)
	slot0.objectReference = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "btnBack"
	slot1 = slot1(slot3, slot4)
	slot0.btnBack = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "viewCtrl"
	slot1 = slot1(slot3, slot4)
	slot0.simpleViewCtrl = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "objectEditRoot"
	slot1 = slot1(slot3, slot4)
	slot3 = slot1
	slot1 = slot1.GetComponent
	slot4 = "USimplePosFollow"
	slot1 = slot1(slot3, slot4)
	slot0.objectEditRoot = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "undoBtn"
	slot1 = slot1(slot3, slot4)
	slot0.undoBtn = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "redoBtn"
	slot1 = slot1(slot3, slot4)
	slot0.redoBtn = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "confirmBtn"
	slot1 = slot1(slot3, slot4)
	slot0.confirmBtn = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "cancelBtn"
	slot1 = slot1(slot3, slot4)
	slot0.cancelBtn = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "withdrawBtn"
	slot1 = slot1(slot3, slot4)
	slot0.withdrawBtn = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "undoBtnHotKeyContent"
	slot1 = slot1(slot3, slot4)
	slot0.undoBtnHotKeyContent = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "redoBtnHotKeyContent"
	slot1 = slot1(slot3, slot4)
	slot0.redoBtnHotKeyContent = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "okBtnHotKeyContent"
	slot1 = slot1(slot3, slot4)
	slot0.okBtnHotKeyContent = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "noBtnHotKeyContent"
	slot1 = slot1(slot3, slot4)
	slot0.noBtnHotKeyContent = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "recycleBtnHotKeyContent"
	slot1 = slot1(slot3, slot4)
	slot0.recycleBtnHotKeyContent = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "tabBtnGridUButton"
	slot1 = slot1(slot3, slot4)
	slot0.tabBtnGridUButton = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "widgetPrompt"
	slot1 = slot1(slot3, slot4)
	slot0.widgetPrompt = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "warningUContainer"
	slot1 = slot1(slot3, slot4)
	slot0.warningUContainer = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "listCurrencyUList"
	slot1 = slot1(slot3, slot4)
	slot0.listCurrencyUList = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "globalEditingUWidget"
	slot1 = slot1(slot3, slot4)
	slot0.globalEditingUWidget = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "operateMobileUContainer"
	slot1 = slot1(slot3, slot4)
	slot0.operateMobileUContainer = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "uIPbHomePlacementUWidget"
	slot1 = slot1(slot3, slot4)
	slot0.uIPbHomePlacementUWidget = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "tabBarUWidget"
	slot1 = slot1(slot3, slot4)
	slot0.tabBarUWidget = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "stateWidget"
	slot1 = slot1(slot3, slot4)
	slot0.stateWidget = slot1
	slot1 = slot0.objectEditRoot
	slot3 = slot1
	slot1 = slot1.GetComponent
	slot4 = "ObjectReference"
	slot1 = slot1(slot3, slot4)
	slot0.itemObjectReference = slot1
	slot1 = slot0.itemObjectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "btnWorldItem"
	slot1 = slot1(slot3, slot4)
	slot0.btnWorldItem = slot1
	slot1 = slot0.itemObjectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "btnWorldItemSimple"
	slot1 = slot1(slot3, slot4)
	slot0.btnWorldItemSimple = slot1
	slot1 = slot0.itemObjectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "btnWorldPet"
	slot1 = slot1(slot3, slot4)
	slot0.btnWorldPet = slot1
	slot1 = slot0.itemObjectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "ownedWidget"
	slot1 = slot1(slot3, slot4)
	slot0.ownedWidget = slot1
	slot1 = slot0.itemObjectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "ownedText"
	slot1 = slot1(slot3, slot4)
	slot0.ownedText = slot1
	slot1 = slot0.itemObjectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "txtNumUSDFText"
	slot1 = slot1(slot3, slot4)
	slot0.txtNumUSDFText = slot1
	slot1 = slot0.itemObjectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "iconCurrencyUImage"
	slot1 = slot1(slot3, slot4)
	slot0.iconCurrencyUImage = slot1

	return
	--- END OF BLOCK #0 ---



end

slot3.findObjects = slot4

return slot3
--- END OF BLOCK #0 ---



