--- BLOCK #0 1-16, warpins: 1 ---
slot0 = require
slot2 = "Guis.UIView"
slot0 = slot0(slot2)
slot1 = require
slot3 = "Core.Framework.Class"
slot1 = slot1(slot3)
slot2 = slot1.LightClass
slot4 = "PetLevelUpView"
slot5 = slot0
slot2 = slot2(slot4, slot5)

slot3 = function(slot0)
	--- BLOCK #0 1-241, warpins: 1 ---
	slot1 = slot0.transform
	slot3 = slot1
	slot1 = slot1.GetComponent
	slot4 = "ObjectReference"
	slot1 = slot1(slot3, slot4)
	slot0.objectReference = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "btnCloseUButton"
	slot1 = slot1(slot3, slot4)
	slot0.btnCloseUButton = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "txtTitleUText"
	slot1 = slot1(slot3, slot4)
	slot0.txtTitleUText = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "imgPetUImage"
	slot1 = slot1(slot3, slot4)
	slot0.imgPetUImage = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "txtLevelUText"
	slot1 = slot1(slot3, slot4)
	slot0.txtLevelUText = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "petDemensionObjectReference"
	slot1 = slot1(slot3, slot4)
	slot0.petDemensionObjectReference = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "upTipsUWidget"
	slot1 = slot1(slot3, slot4)
	slot0.upTipsUWidget = slot1
	slot1 = slot0.objectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "textUSDFText"
	slot1 = slot1(slot3, slot4)
	slot0.textUSDFText = slot1
	slot1 = slot0.petDemensionObjectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "hpNum"
	slot1 = slot1(slot3, slot4)
	slot0.hpNum = slot1
	slot1 = slot0.petDemensionObjectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "atkNum"
	slot1 = slot1(slot3, slot4)
	slot0.atkNum = slot1
	slot1 = slot0.petDemensionObjectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "defNum"
	slot1 = slot1(slot3, slot4)
	slot0.defNum = slot1
	slot1 = slot0.petDemensionObjectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "regenNum"
	slot1 = slot1(slot3, slot4)
	slot0.regenNum = slot1
	slot1 = slot0.petDemensionObjectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "defMagNum"
	slot1 = slot1(slot3, slot4)
	slot0.defMagNum = slot1
	slot1 = slot0.petDemensionObjectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "atkMagNum"
	slot1 = slot1(slot3, slot4)
	slot0.atkMagNum = slot1
	slot1 = slot0.petDemensionObjectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "hpCmp"
	slot1 = slot1(slot3, slot4)
	slot0.hpCmp = slot1
	slot1 = slot0.petDemensionObjectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "atkCmp"
	slot1 = slot1(slot3, slot4)
	slot0.atkCmp = slot1
	slot1 = slot0.petDemensionObjectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "defCmp"
	slot1 = slot1(slot3, slot4)
	slot0.defCmp = slot1
	slot1 = slot0.petDemensionObjectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "regenCmp"
	slot1 = slot1(slot3, slot4)
	slot0.regenCmp = slot1
	slot1 = slot0.petDemensionObjectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "defMagCmp"
	slot1 = slot1(slot3, slot4)
	slot0.defMagCmp = slot1
	slot1 = slot0.petDemensionObjectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "atkMagCmp"
	slot1 = slot1(slot3, slot4)
	slot0.atkMagCmp = slot1
	slot1 = slot0.petDemensionObjectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "hpLevelCmp"
	slot1 = slot1(slot3, slot4)
	slot0.hpLevelCmp = slot1
	slot1 = slot0.petDemensionObjectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "atkLevelCmp"
	slot1 = slot1(slot3, slot4)
	slot0.atkLevelCmp = slot1
	slot1 = slot0.petDemensionObjectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "defLevelCmp"
	slot1 = slot1(slot3, slot4)
	slot0.defLevelCmp = slot1
	slot1 = slot0.petDemensionObjectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "regenLevelCmp"
	slot1 = slot1(slot3, slot4)
	slot0.regenLevelCmp = slot1
	slot1 = slot0.petDemensionObjectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "defMagLevelCmp"
	slot1 = slot1(slot3, slot4)
	slot0.defMagLevelCmp = slot1
	slot1 = slot0.petDemensionObjectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "atkMagLevelCmp"
	slot1 = slot1(slot3, slot4)
	slot0.atkMagLevelCmp = slot1
	slot1 = slot0.petDemensionObjectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "hpLv"
	slot1 = slot1(slot3, slot4)
	slot0.hpLv = slot1
	slot1 = slot0.petDemensionObjectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "atkLv"
	slot1 = slot1(slot3, slot4)
	slot0.atkLv = slot1
	slot1 = slot0.petDemensionObjectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "defLv"
	slot1 = slot1(slot3, slot4)
	slot0.defLv = slot1
	slot1 = slot0.petDemensionObjectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "regenLv"
	slot1 = slot1(slot3, slot4)
	slot0.regenLv = slot1
	slot1 = slot0.petDemensionObjectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "defMagLv"
	slot1 = slot1(slot3, slot4)
	slot0.defMagLv = slot1
	slot1 = slot0.petDemensionObjectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "atkMagLv"
	slot1 = slot1(slot3, slot4)
	slot0.atkMagLv = slot1
	slot1 = slot0.petDemensionObjectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "defaultRadar"
	slot1 = slot1(slot3, slot4)
	slot0.defaultRadar = slot1
	slot1 = slot0.petDemensionObjectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "addedRadar"
	slot1 = slot1(slot3, slot4)
	slot0.addedRadar = slot1
	slot1 = slot0.petDemensionObjectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "hpValueAdd"
	slot1 = slot1(slot3, slot4)
	slot0.hpValueAdd = slot1
	slot1 = slot0.petDemensionObjectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "atkValueAdd"
	slot1 = slot1(slot3, slot4)
	slot0.atkValueAdd = slot1
	slot1 = slot0.petDemensionObjectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "defValueAdd"
	slot1 = slot1(slot3, slot4)
	slot0.defValueAdd = slot1
	slot1 = slot0.petDemensionObjectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "regenValueAdd"
	slot1 = slot1(slot3, slot4)
	slot0.regenValueAdd = slot1
	slot1 = slot0.petDemensionObjectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "defMagValueAdd"
	slot1 = slot1(slot3, slot4)
	slot0.defMagValueAdd = slot1
	slot1 = slot0.petDemensionObjectReference
	slot3 = slot1
	slot1 = slot1.GetRefValue
	slot4 = "atkMagValueAdd"
	slot1 = slot1(slot3, slot4)
	slot0.atkMagValueAdd = slot1

	return
	--- END OF BLOCK #0 ---



end

slot2.findObjects = slot3

slot3 = function(slot0)
	--- BLOCK #0 1-1, warpins: 1 ---
	return
	--- END OF BLOCK #0 ---



end

slot2.initView = slot3

return slot2
--- END OF BLOCK #0 ---



