--- BLOCK #0 1-14, warpins: 1 ---
slot0 = require
slot2 = "Core.Framework.Class"
slot0 = slot0(slot2)
slot1 = require
slot3 = "Guis.UIView"
slot1 = slot1(slot3)
slot2 = slot0.LightClass
slot4 = "RogLevelSelectView"
slot5 = slot1
slot2 = slot2(slot4, slot5)

slot3 = function(slot0)
	--- BLOCK #0 1-171, warpins: 1 ---
	slot1 = slot0.transform
	slot3 = slot1
	slot1 = slot1.GetComponent
	slot4 = "ObjectReference"
	slot1 = slot1(slot3, slot4)
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "rootComponent"
	slot2 = slot2(slot4, slot5)
	slot0.rootComponent = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "btnShop"
	slot2 = slot2(slot4, slot5)
	slot0.btnShop = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "btnClose"
	slot2 = slot2(slot4, slot5)
	slot0.btnClose = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "btnInfoUButton"
	slot2 = slot2(slot4, slot5)
	slot0.btnInfoUButton = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "iconUp3UContainer"
	slot2 = slot2(slot4, slot5)
	slot0.iconUp3UContainer = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "btnSwitchUButton"
	slot2 = slot2(slot4, slot5)
	slot0.btnSwitchUButton = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "cycleUCountDown"
	slot2 = slot2(slot4, slot5)
	slot0.cycleUCountDown = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "progressUBaseText"
	slot2 = slot2(slot4, slot5)
	slot0.progressUBaseText = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "currencyUList"
	slot2 = slot2(slot4, slot5)
	slot0.currencyUList = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "btnResetUButton"
	slot2 = slot2(slot4, slot5)
	slot0.btnResetUButton = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "talentUList"
	slot2 = slot2(slot4, slot5)
	slot0.talentUList = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "talentInfoUComponent"
	slot2 = slot2(slot4, slot5)
	slot0.talentInfoUComponent = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "talentIconUImage"
	slot2 = slot2(slot4, slot5)
	slot0.talentIconUImage = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "talentNameUBaseText"
	slot2 = slot2(slot4, slot5)
	slot0.talentNameUBaseText = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "talentDescUBaseText"
	slot2 = slot2(slot4, slot5)
	slot0.talentDescUBaseText = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "talentOwnUBaseText"
	slot2 = slot2(slot4, slot5)
	slot0.talentOwnUBaseText = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "talentConsumeUBaseText"
	slot2 = slot2(slot4, slot5)
	slot0.talentConsumeUBaseText = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "talentTipsUList"
	slot2 = slot2(slot4, slot5)
	slot0.talentTipsUList = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "btnActiveUButton"
	slot2 = slot2(slot4, slot5)
	slot0.btnActiveUButton = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "rootAnimation"
	slot2 = slot2(slot4, slot5)
	slot0.rootAnimation = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "normalLevelUList"
	slot2 = slot2(slot4, slot5)
	slot0.normalLevelUList = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "highLevelUList"
	slot2 = slot2(slot4, slot5)
	slot0.highLevelUList = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "conditionAnimation"
	slot2 = slot2(slot4, slot5)
	slot0.conditionAnimation = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "weeklyUButton"
	slot2 = slot2(slot4, slot5)
	slot0.weeklyUButton = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "titleTabUList"
	slot2 = slot2(slot4, slot5)
	slot0.titleTabUList = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "btnNextTipUButton"
	slot2 = slot2(slot4, slot5)
	slot0.btnNextTipUButton = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "dailyRewardUButton"
	slot2 = slot2(slot4, slot5)
	slot0.dailyRewardUButton = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "dailyRewardUBaseText"
	slot2 = slot2(slot4, slot5)
	slot0.dailyRewardUBaseText = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "dailyReward1UBaseText"
	slot2 = slot2(slot4, slot5)
	slot0.dailyReward1UBaseText = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "nextTipUBaseText"
	slot2 = slot2(slot4, slot5)
	slot0.nextTipUBaseText = slot2
	slot4 = slot1
	slot2 = slot1.GetRefValue
	slot5 = "shopUBaseText"
	slot2 = slot2(slot4, slot5)
	slot0.shopUBaseText = slot2
	slot2 = slot0.btnActiveUButton
	slot4 = slot2
	slot2 = slot2.GetComponent
	slot5 = "ObjectReference"
	slot2 = slot2(slot4, slot5)
	slot5 = slot2
	slot3 = slot2.GetRefValue
	slot6 = "txtNameUText"
	slot3 = slot3(slot5, slot6)
	slot0.btnActiveUText = slot3

	return
	--- END OF BLOCK #0 ---



end

slot2.findObjects = slot3

return slot2
--- END OF BLOCK #0 ---



